### ISSUE TITLE
errore

### ISSUE THREAD

**Issue by jessica-bondavalli** [UniprJRC/DSconMATLAB#10]
pag 312
linea 8
rimpiazzare
% con i valoro di mu e Sigma specificati
con
% con i valori di mu e Sigma specificati

**Comment by MarcoRianiUNIPR** [comment]
Chiudo issue in quanto la sua segnalazione è stata inserita a suo tempo nella pagina di errata corrige

p. 312 riga 8 del codice
Rimpiazzare
% con i valoro di mu e Sigma specificati
con
% con i valori di mu e Sigma specificati
Segnalato da Jessica Bondavalli
