### ISSUE TITLE
Errore formula pag. 157

### ISSUE THREAD

**Issue by Gioele090101** [UniprJRC/DSconMATLAB#103]
Riga 8 

convert2montly
La formula corretta dovrebbe essere: convert2monthly

**Comment by UniprJRC** [comment]
Aggiunto in errata corrige

p.157 riga 8 (segnalato da [Gioele090101](https://github.com/Gioele090101) 29/09/2023)
Rimpiazzare
... con la sintassi convert2montly(Y,...
con
... con la sintassi convert2monthly(Y,...
