### ISSUE TITLE
Errore esercizio HW 3.10 pag 134

### ISSUE THREAD

**Issue by federico-baio** [UniprJRC/DSconMATLAB#107]
Nelle ultime righe dell'esercizio 3.10 è erroneamente riportato: "... ci siano gli iscritti prim**i** e dopo il 2020." 
invece di "... ci siano gli iscritti prim**a** e dopo il 2020."

**Comment by UniprJRC** [comment]
Aggiunto in errata corrige

p. 134 penultima riga dell'Esercizio HW 3.10 (segnalato da [federico-baio](https://github.com/federico-baio) 30/09/2023)
Rimpiazzare
...primi e dopo il 2020, ...
con
...prima e dopo il 2020, ...
