### ISSUE TITLE
Errore di battitura che non ostacola la comprensione 

### ISSUE THREAD

**Issue by ValeConcari** [UniprJRC/DSconMATLAB#108]
Manca la maiuscola alla fine di pagina 157

**Comment by UniprJRC** [comment]
Mi raccomando, prima di scrivere, di consultare la pagina di errata corrige
Questo typo era già stato segnalato il 27/09/2023

p. 157 ultima riga (segnalato da [Francesca Pia Sarno](https://github.com/FrancescaPiaSarno) 27/09/2023)
Rimpiazzare
... Banca d'Italia). la ...
con
... Banca d'Italia). La ...

**Comment by UniprJRC** [comment]
Segnalazione già effettuata issue chiuso
