### ISSUE TITLE
Errore grammaticale

### ISSUE THREAD

**Issue by Riccardo010401** [UniprJRC/DSconMATLAB#11]
Pag. 40, ultima riga del paragrafo 1.5.2. 
Necessita di uso del condizionale
% sostituire con "sarebbe potuto essere scritto come" o "avrebbe potuto essere scritto come". Quest'ultima modalità è considerata la più corretta dall'Accademia della Crusca.

**Comment by MarcoRianiUNIPR** [comment]
Ok ne terremo conto nella prossima edizione del libro. Grazie per la segnalazione
