### ISSUE TITLE
Errore nella soluzione dell'esercizio HW5.11 a pagina 202

### ISSUE THREAD

**Issue by Alematassa02** [UniprJRC/DSconMATLAB#111]
Salve professore mentre mi esercitavo ho riscontrato un errore tra le soluzioni del libro, più precisamente nell'esercizio HW5.11 a pagina 202 in quanto eseguendo il codice della soluzione mi dava un errore. In allegato riporto la soluzione del libro e di seguito la mia eventuale correzione.

![WhatsApp Image 2023-09-30 at 4 08 33 PM](https://github.com/UniprJRC/DSconMATLAB/assets/146077898/0f03346d-dc4c-4fb2-81e9-64b1b4db4f0c)

<img width="653" alt="Schermata 2023-09-30 alle 16 05 12" src="https://github.com/UniprJRC/DSconMATLAB/assets/146077898/6e0e81fc-5fd5-41cb-a680-ee891403490f">

**Comment by UniprJRC** [comment]
Le confermo che la sua soluzione è sbagliata.

Ovviamente xSottoMEDIA non può essere uguale a x

xSottoMEDIA=x(x<MEDIA);
sono i rendimenti che sono risultati inferiori alla media (in questo esempio sono 13).

L'unica possibilità che posso intravedere che le dava errore poteva essere la seguente
![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/fdce7580-8a4f-41b2-9a83-561a22a987e9)

In questo caso MATLAB semplicemente mi sta dicendo che occorre reinizializzare il generatore di numeri casuali a default).

Nella schermata che le ho mostrato sopra ho semplicemente scritto nella command (come indicato da MATLAB)

rng default 

e ho rifatto il run del file.

In conclusione: la soluzione proposta è corretta.
Per favore commenti quello che ho scritto per capire se sono stato chiaro.

**Comment by UniprJRC** [comment]
Il sito di Giappichelli ora riporta la versione corretta. l'issue viene chiuso
