### ISSUE TITLE
Errore nella soluzione dell'esercizio di riepilogo HW 1.2

### ISSUE THREAD

**Issue by ElenaMarongiu** [UniprJRC/DSconMATLAB#112]
L'esercizio richiede che nell'elemento 2,3 di un cell array deve contenere un vettore colonna composto dai numeri 11,14,17,...,32
la soluzione dell'esercizio sul sito di Giappichelli da come scrittura su MATLAB el23=(11:14:32)'
la scrittura su Matlab dovrebbe invece essere el23=(11:3:32)'

**Comment by UniprJRC** [comment]
Lei ha assolutamente ragione. Brava!
Lascio aperto questo issue finché non viene corretto nel sito di Giappichelli

**Comment by UniprJRC** [comment]
Issue chiuso in quanto la soluzione corretta è nel sito di Giappichelli
