### ISSUE TITLE
errore esercizio 1.2

### ISSUE THREAD

**Issue by catalinagizzi** [UniprJRC/DSconMATLAB#113]
nell'esercizio 1.2 si richiede che nell'elemento 2x3 si deve contenere un vettore colonna composto da numeri 11, 14,17... 32.
nella soluzione sul sito della Giappichelli è: [11:14:32]' , che da come risultato un vettore colonna [11 25]
la soluzione corretta dovrebbe essere  [11:3:32]'

**Comment by UniprJRC** [comment]
Veda quello che ho appena scritto nell'issue 25
