### ISSUE TITLE
errore pag 149 esercizio 4.4

### ISSUE THREAD

**Issue by giorgialusardi** [UniprJRC/DSconMATLAB#115]
Nella prima riga correggere **timetible** con **timetable**

**Comment by UniprJRC** [comment]
Mi raccomando prima di scrivere di consultare la pagina di errata corrige per vedere se un refuso era già stato segnalato
----------------------------------------------------------------
p. 149 prima riga dell'Esercizio 4.4 (segnalato da fabiolacersosimo 28/09/2023)
Rimpiazzare
Partendo dalla timetible TT creata...
con
Partendo dalla timetable TT creata...

**Comment by UniprJRC** [comment]
Segnalazione già effettuata issue chiuso
