### ISSUE TITLE
Errore di battitura pagina 142

### ISSUE THREAD

**Issue by matteocardi16** [UniprJRC/DSconMATLAB#116]
Errore di battitura che non ostacola la comprensione alla riga 7: il nome del file "SummarioMio.m" non corrisponde a quello presente nella figura 4.4.
Sostituire il nome del file con "SummaryMio.m".

**Comment by UniprJRC** [comment]
Lei è davvero molto bravo!

Grazie per la segnalazione. Appena inserita in errata corrige

p. 142 riga 7 (segnalato da [matteocardi16](https://github.com/matteocardi16) 30/09/2023)
Rimpiazzare
... (v. ad esempio il file SummarioMio.m nella Figura 4.4).
con
... (v. ad esempio il file SummaryMio.m nella Figura 4.4).
