### ISSUE TITLE
Errore di battitura pag. 159

### ISSUE THREAD

**Issue by matteocardi16** [UniprJRC/DSconMATLAB#118]
Errore di battitura che non ostacola la comprensione nelle ultime righe: sostituire "quello vista sopra" con "quello visto sopra".
(Nella quarta riga partendo dal basso)

**Comment by UniprJRC** [comment]
Aggiunto

p. 159 terzultima riga prima dell'Esercizio 4.9 (segnalato da [matteocardi16](https://github.com/matteocardi16) 01/10/2023)
Rimpiazzare
...uguale a quello vista sopra...
con
...uguale a quello visto sopra...
