### ISSUE TITLE
Errore esercizio 2.3

### ISSUE THREAD

**Issue by Riccardo010401** [UniprJRC/DSconMATLAB#12]
Pag. 65 esercizio 2.3.

Nel testo dell'esercizio è richiesto il codice per trovare gli elementi di 3 linee sotto la diagonale primcipale. Nell'esecuzione viene eseguito il codice per calcolare gli elementi di 2 linee sotto la diagonale

**Comment by MarcoRianiUNIPR** [comment]
Aggiunto il nome Riccardo010401 nella pagina di errata corrige


p. 65, nel testo dell'esercizio 2.3 la riga
... e gli elementi di 3 linee sotto la diagonale principale in un vettore denominato b.
deve essere sostituito con
... e gli elementi di 2 linee sotto la diagonale principale in un vettore denominato b.
Segnalato da Nicole Salvadori e Riccardo010401.
