### ISSUE TITLE
Taglio del codice nell'esercizio HW 5.12

### ISSUE THREAD

**Issue by Alematassa02** [UniprJRC/DSconMATLAB#120]
Salve Prof., 
è possibile che, anche nelle soluzioni di Giappichelli dell'esercizio HW 5.12 pag 203, sia stato tagliato un pezzo di codice? 
Come da screen allegato in questo modo il programma funziona. Viceversa, nella soluzione che viene data dal libro no. 
Più precisamente credo che nelle soluzioni non vi sia il pezzo di codice seguente : xSottoMAR=x(x<MAR);

Grazie anticipatamente,
Saluti.

<img width="1047" alt="Schermata 2023-10-02 alle 09 51 27" src="https://github.com/UniprJRC/DSconMATLAB/assets/146077898/c0f8a298-7aa0-4033-9b39-925b9552abad">

**Comment by UniprJRC** [comment]
nel sito di Giappichelli io vedo

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/3acd072e-fc7a-4a65-a98c-77816d8e852e)

La riga di codice quindi c'è. Magari lei aveva la versione vecchia ancora in cache nel sito di Giappichelli? Mi faccia sapere

**Comment by Alematassa02** [comment]
Si, non mi si era aggiornato il libro online.
La ringrazio

**Comment by UniprJRC** [comment]
Issue chiuso
