### ISSUE TITLE
 Errori di battitura che possono ostacolare la comprensione

### ISSUE THREAD

**Issue by Alematassa02** [UniprJRC/DSconMATLAB#122]
Salve, 
a pagina 211 quando viene scritto il codice relativo a FSR di Toolbox non è stata messa una parentesi tonda a fine codice.
La forma corretta sarebbe: out=FSR(Xadd(:,2), Xadd(:,1))

Spero di essere stata di aiuto.
Saluto.

**Comment by UniprJRC** [comment]
@Alematassa02 Gli issue chiusi sono già stati inseriti in errata corrige.
Ad esempio

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/a9790f17-5414-4545-8453-da2d9c9d51f7)

Lascio aperto  l'issue poiché non vorrei che lei lo riapra di nuovo.
Mi faccia sapere se è tutto a posto

**Comment by Alematassa02** [comment]
Si tutto a posto. Non avevo capito che fosse stato chiuso. Mi scusi.
Saluti
