### ISSUE TITLE
Errore es 4.4, pagina 149

### ISSUE THREAD

**Issue by Dallo2001** [UniprJRC/DSconMATLAB#126]
Nella consegna dell'esercizio si parla di estrarre le date che si riferiscono alle date di nascita DOPO il giorno 20.
Mentre alla riga 7, dove viene creato il booleano riguardante i giorni, viene scritto:
giorni=TT.......Day>=20
Viene dunque compreso il 20, mentre nella consegna si parla di DOPO il giorno 20.

**Comment by UniprJRC** [comment]
Appena aggiunto in errata corrige

p. 149 seconda riga dell'Esercizio 4.4 (segnalato da [Dallo2001](https://github.com/Dallo2001) 03/10/2023)
Rimpiazzare
...date di nascita dopo il giorno 20 ...
con
...date di nascita dopo il giorno 19 ...
