### ISSUE TITLE
Errore di battitura che non ostacola la comprensione

### ISSUE THREAD

**Issue by ValentinaSantucci1** [UniprJRC/DSconMATLAB#127]
Alla fine della pagina 156 e all'inizio di pagina 157, più nello specifico nella riga 1 di pagina 157 manca un **"."** dopo intervalli temporali.

**Comment by UniprJRC** [comment]
Mi raccomando di controllare la pagina di errata corrige prima di scrivere

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/111cee1b-e111-4d26-b080-d18d462216b6)

**Comment by UniprJRC** [comment]
Issue chiuso in quanto segnalazione già effettuata
