### ISSUE TITLE
Errore ortografico che non impedisce la comprensione pagina 157

### ISSUE THREAD

**Issue by ValentinaSantucci1** [UniprJRC/DSconMATLAB#128]
A pagina 157 è presente un errore ortografico. 
Nella quinta riga, circa verso la fine, c'è scritto "inserire" invece di "inserisce".

**Comment by UniprJRC** [comment]
Mi raccomando di controllare la pagina di errata corrige prima di scrivere

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/26ca0149-fa45-45d4-b32c-6dc08536e5ff)

**Comment by UniprJRC** [comment]
Issue chiuso in quanto era già stato segnalato
