### ISSUE TITLE
Errore ortografico che non impedisce la comprensione

### ISSUE THREAD

**Issue by ValentinaSantucci1** [UniprJRC/DSconMATLAB#129]
Pagina 157, ultima riga manca una "L".
La frase corretta sarebbe: "....(inclusa la Banca d'Italia). La funzione fred....."

**Comment by UniprJRC** [comment]
Stessa osservazione di prima: terzo reminder

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/95b1f03c-7f24-433a-bbe6-d1a9642a0d3a)

**Comment by UniprJRC** [comment]
Issue chiuso in quanto segnalazione già effettuata
