### ISSUE TITLE
Errore esercizio 2.16

### ISSUE THREAD

**Issue by Riccardo010401** [UniprJRC/DSconMATLAB#13]
Pag. 77/78
- Nel testo dell'esercizio viene richiesta la contaminazione solo dei valori 5 e 8. Nell'esecuzione vengono contaminate interamente le righe 5 e 8.
- Nel codice alla riga 6 viene proposta un'alternativa di soluzione nella quale sono invertite mu e sigma.

**Comment by MarcoRianiUNIPR** [comment]
Quando di parla di osservazioni (in questo caso multivariate) si intende sempre una determinata della matrice di dimensione nxp

Con riferimento alla sua seconda osservazione (assolutamente corretta)

nella pagina di errata corrige ho aggiunto il suo nome

**Comment by sayefyonko** [comment]
saleve bouna sera prof io no recuto di scaricare il fail di github perche ogni volta scarica dopo lo metto !git mi ucere non vailed
