### ISSUE TITLE
Errore di battitura nel file "fitdistIntro.m" della cartella "capDistribuzioni"

### ISSUE THREAD

**Issue by matteocardi16** [UniprJRC/DSconMATLAB#130]
Nella riga 3 del codice vengono indicati "2 gradi di libertà" mentre l'esercizio ne prevede 5 (nu=5): cambiare in "5 gradi di libertà".

**Comment by UniprJRC** [comment]
Nel file fitdistIntro.m io vedo questo
![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/0fb8eda4-be0b-4dbc-a508-20079c947611)

Credo che lei non abbia la versione aggiornata del codice. dx mouse source control pull. Mi faccia sapere

**Comment by matteocardi16** [comment]
Ho fatto il source control pull e anche io vedo la stessa cosa
nell'immagine da lei allegata. Non capisco perché nel commento ci sono 2
gradi di libertà e nell'esercizio invece sono 5.



Il giorno mar 3 ott 2023 alle ore 18:17 University of Parma (Robust
Statistics Academy, RoSA) and Joint Research Centre of the European
Commission ***@***.***> ha scritto:

**Comment by UniprJRC** [comment]
Ho capito ora che lei si riferiva all'intestazione

Dati generati da una T con 2 gradi di libertà.

La sua osservazione è corretta. Il file è stato corretto e aggiornato.
