### ISSUE TITLE
Aggiunta warning nel file "fitdistIntro.m" della cartella "capDistribuzioni"

### ISSUE THREAD

**Issue by matteocardi16** [UniprJRC/DSconMATLAB#131]
Alla riga 21 del codice manca il valore assoluto di X "abs(X)".

**Comment by UniprJRC** [comment]
Un commento è stato aggiunto

%% Viene adattato un modello Weibull
% Viene applicato il valore assoluto in quanto la distribuzione di Weibull
% è definita nell'intervallo x [0 Inf).
stimeW=fitdist(abs(X),"Weibull");
disp(stimeW)
