### ISSUE TITLE
Esercizio 5.9

### ISSUE THREAD

**Issue by catalinagizzi** [UniprJRC/DSconMATLAB#132]
Nell'esercizio 5.9 sul libro viene richiesto di rappresentare la funzione z nei punti x e y della griglia -2, -1.9, ... , 2.
Nella soluzione sul libro, in cui viene usato il codice mesh(z), il grafico appare così:
![Screenshot matlab 1](https://github.com/UniprJRC/DSconMATLAB/assets/146561555/888ef1cb-608a-4dd1-b37a-ac621126b80d)
invece usando il codice mesh(x,y,z):
![Screenshot matlab 2](https://github.com/UniprJRC/DSconMATLAB/assets/146561555/69357e2f-6972-4d1b-8b0e-a426f2fad8ea)
poichè viene richiesto di mostrarlo nella griglia -2,2 , è sbagliato scrivere solo mesh(z)?

**Comment by UniprJRC** [comment]
Sì confermo che scrivere solo mesh(z) è sbagliato poiché in questo caso MATLAB inserisce come default sugli assi di base le sequenze dei numeri naturali e non l'intervallo [-2 2]. Nell copertina del libro il codice è scritto correttamente
mesh(x,y,z). Nell'esercizio 5.9 (come ha fatto notare lei) x e y sono stati erroneamente omessi. 
Brava! questa è una segnalazione per la sezione "refusi che possono ostacolare la comprensione". 

La pagina di errata corrige è stata aggiornata

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/4c3ff04f-8a41-4886-b504-0aaaaa91b4f1)

**Comment by catalinagizzi** [comment]
Ho riscontrato lo stesso errore nell'esercizio di riepilogo 5.9 a pagina 202. Nel libro viene richiesto di rappresentare la funzione nei punti della griglia x e y, ma nelle soluzioni sul sito della giappichelli è scritto mesh(z).

**Comment by UniprJRC** [comment]
Ha assolutamente ragione. Lascio l'issue aperto fino a quando non viene corretto il refuso nel sito di Giappichelli

**Comment by UniprJRC** [comment]
Issue chiuso in quanto la versione corretta è stata inserita nel sito di Giappichelli
