### ISSUE TITLE
errore/imprecisione file nel capImportazioni

### ISSUE THREAD

**Issue by OrlandiMartina** [UniprJRC/DSconMATLAB#133]
![Screenshot (160)](https://github.com/UniprJRC/DSconMATLAB/assets/145756214/c09ea98d-47de-4037-8f51-f994f39dd40b)
Nel percorso DSconMATLAB>matlabfiles>capImportazioni è presente un'imprecisione nel titolo dei seguenti  file: readQuartelyFinances.m   e readQuartelyFinancesComeTimeTable.m

Mancanza della lettera r
readQuarte**r**lyFinances.m   e readQuarte**r**lyFinancesComeTimeTable.m

**Comment by UniprJRC** [comment]
La sua segnalazione è corretta. 
Grazie mille brava!

La r ora è stata aggiunta. Faccia il pull per avere il file con la nuova denominazione
