### ISSUE TITLE
Errore che ostacola la compresione Es.7.1 pag.247

### ISSUE THREAD

**Issue by Alematassa02** [UniprJRC/DSconMATLAB#134]
Salve, volevo segnalare che nel testo dell'esercizio 7.1 di pagina 247 vi è un errore nella formula della costruzione della matrice di covarianza tramite doppio ciclo for.
Più precisamente sotto la radice viene scritto var(Xs)var(Yj).. mentre dovrebbe essere var(Xs)var(Xj).
Infatti anche nella soluzione dell'esercizio viene usato var(Xs)var(Xj).

Saluti.

**Comment by UniprJRC** [comment]
Aggiunto in errata corrige

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/a5d5952e-ecce-42bb-8492-a3040aba8999)
