### ISSUE TITLE
Errore di battitura che non ostacola la comprensione

### ISSUE THREAD

**Issue by Alematassa02** [UniprJRC/DSconMATLAB#135]
Salve, nel testo dell'esercizio HW7.3 a pag.248,  riga 12 , sostituire -> "seri**a**" con "seri**e**" . 

Saluti.

**Comment by UniprJRC** [comment]
![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/95d8d98d-651a-41c3-94ac-ecf40d2e83e2)
