### ISSUE TITLE
Errore nell'esercizio di riepilogo  5.6

### ISSUE THREAD

**Issue by catalinagizzi** [UniprJRC/DSconMATLAB#136]
Segnalo errore nell'esercizio di riepilogo 5.6 pagina 200 in cui viene richiesto di estrarre un campione dalla distribuzione T(8), quindi i gradi di libertà sarebbero 8. Nella soluzione caricata su giappichelli, vengono impostati  i gradi di libertà pari a 5
![Screenshot matlab soluzione esercizio 5 6](https://github.com/UniprJRC/DSconMATLAB/assets/146561555/c162ecc6-61cb-4c50-b4d2-e398c4739679)

**Comment by UniprJRC** [comment]
La sua osservazione è corretta. Lascio aperto questo issue fino a quando il refuso non sarà corretto nel sito di Giappichelli

**Comment by UniprJRC** [comment]
L'issue viene chiuso in quanto corretto nel sito di Giappichelli. Grazie ancora per la segnalazione
