### ISSUE TITLE
Errore che non ostacola la comprensione

### ISSUE THREAD

**Issue by Alematassa02** [UniprJRC/DSconMATLAB#137]
Salve, segnalo che nella soluzione dell'esercizio HW 7.4 quando viene commentata la correlazione tra le variabili, più precisamente nella riga 6 del commento,  bisognerebbe scrivere "... corrispondono **valori** elevati di (ad esempio) lunghezza del naso". Nella soluzione non viene messa la parola "**valori**".

Saluti.

**Comment by UniprJRC** [comment]
Sì grazie mille.

Nella versione rivista (che tra breve sarà caricata nel sito della Giappichelli) abbiamo fatto un restyling ti tutti i commenti,

Di seguito il confronto tra la versione del file che vede in questo momento e quella che vedrà tra breve

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/ddc27a78-9384-4279-874d-f2907fd6ab58)

**Comment by UniprJRC** [comment]
L'issue viene chiuso in quanto la pagina nel sito di Giappichelli è stata aggiornata
