### ISSUE TITLE
Errore esercizio 6.4

### ISSUE THREAD

**Issue by catalinagizzi** [UniprJRC/DSconMATLAB#138]
Nell'esercizio 6.4 a pagina 220 viene richiesto di generare 50 numeri casuali da U(3,30).
Sia sul libro sia nel file su Matlab  jbtestPval.m nella prima riga è stato scritto n=100; 
![Screenshot matlab 6 4](https://github.com/UniprJRC/DSconMATLAB/assets/146561555/2189d338-207e-4cdb-a945-b84cd7f01e22)

**Comment by UniprJRC** [comment]
Aggiunto in errata corrige. Grazie per la segnalazione
