### ISSUE TITLE
errori ortografici

### ISSUE THREAD

**Issue by miriamcarbonaro** [UniprJRC/DSconMATLAB#14]
sezione analisi dei dati per il marketing

![errore ortografico6](https://user-images.githubusercontent.com/113711843/198343229-67a16e9c-156d-4700-877d-3f5fe5ee89c7.png)
![errore ortografico5](https://user-images.githubusercontent.com/113711843/198343233-d5e80f3f-1d84-48b7-95e2-b0c22ba9b1c4.png)
![erroreortografico4](https://user-images.githubusercontent.com/113711843/198343234-55a00536-1024-4b65-b831-f810f246f509.png)

**Comment by MarcoRianiUNIPR** [comment]
Errori corretti
Grazie per le segnalazioni
