### ISSUE TITLE
Errore nell'esercizio di riepilogo 5.8 pag.202

### ISSUE THREAD

**Issue by matteocardi16** [UniprJRC/DSconMATLAB#141]
Incongruenza nella soluzione sul sito "biblioteca.giappichelli.it".
Nel testo dell'esercizio il valore di lambda è pari a 2, mentre nella soluzione viene indicato un lambda pari a 5.
![image](https://github.com/UniprJRC/DSconMATLAB/assets/144787661/4bc416fa-942c-4189-ad43-74ce879b32fb)

**Comment by UniprJRC** [comment]
L'osservazione è corretta.

La sua segnalazione mi ha dato lo spunto per scrivere il codice in modo tale che il titolo sia dinamico.

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/28341d30-c139-4c7d-a8b1-dc7c84e3a211)

Lascio aperto questo issue fino a quando la versione corretta verrà inserita nel sito di Giappichelli

**Comment by UniprJRC** [comment]
issue chiuso in quanto la correzione è stata inserita nel sito di Giappichelli
