### ISSUE TITLE
errore pagina 172

### ISSUE THREAD

**Issue by ElenaMarongiu** [UniprJRC/DSconMATLAB#143]
L'esercizio 5.3 chiede di calcolare il valore che lascia alla sua destra una probabilità di 2.5%.
Nell'esecuzione dell'esercizio su matlab c'è scritto quantile 0.975 (valore che lascia alla sua sinistra una probabilità di 2.5 per cento), in realtà il valore 0.975 lascia alla sua Destra una probabilità di 2.5% 
![esercizio 5 3](https://github.com/UniprJRC/DSconMATLAB/assets/144916277/726456bd-0f62-46a7-bcba-e13a72766676)
 il valore 0.975 lascia alla sua Destra una probabilità di 2.5%

**Comment by UniprJRC** [comment]
Segnalazione corretta ad aggiunta all'errata corrige
