### ISSUE TITLE
Errore colorazione codice pagina 189

### ISSUE THREAD

**Issue by ElenaMarongiu** [UniprJRC/DSconMATLAB#144]
Nell'esercizio 5.8 è presente il codice Matlab rng default, che sul libro assume la colorazione nera. Scrivendo il codice su Matlab pero la scritta del codice "default" è diversa.
![codice matlab](https://github.com/UniprJRC/DSconMATLAB/assets/144916277/29807297-83be-4e28-aa08-ff40945db518)
![esercizio 5 8](https://github.com/UniprJRC/DSconMATLAB/assets/144916277/70793726-e427-4fae-97fc-16b13cbce8a4)

**Comment by UniprJRC** [comment]
Brava. La sua segnalazione è corretta ed è stata inserita errata corrige

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/6f48419a-aad1-451a-b5c5-a1a027cde280)
