### ISSUE TITLE
soluzioni Giappichelli, HW 5.8

### ISSUE THREAD

**Issue by federico-baio** [UniprJRC/DSconMATLAB#145]
Nella soluzione sul sito di Giappichelli dell'esercizio HW 5.8, come parametro di scala per la distribuzione, invece di 2 come indicato nella consegna, viene utilizzato un parametro di scala pari a 5.

**Comment by UniprJRC** [comment]
Già segnalato veda issue #141 

Chiudo pertanto questo issue
