### ISSUE TITLE
errore che non ostacola la comprensione

### ISSUE THREAD

**Issue by Alematassa02** [UniprJRC/DSconMATLAB#151]
Salve, 
nel testo dell'esercizio 9.9 a pagina 296, nella riga 2 sostituire
"ampiezza dei **s**epali" con "ampiezza dei **p**etali".

Saluti.

**Comment by Alematassa02** [comment]
Non sapendo come annullare l'issue scrivo qui che il mio commento è errato, in quanto pensandoci i "sepali" esistono. 

Mi scusi, saluti.

**Comment by UniprJRC** [comment]
Issue chiuso
