### ISSUE TITLE
Sito Giappichelli, Esercizio HW6.4

### ISSUE THREAD

**Issue by federico-baio** [UniprJRC/DSconMATLAB#158]
Nel testo dell'esercizio viene richiesto di calcolare tra i vari valori la mediana, ma nella soluzione dell'esercizio sul sito, al posto della mediana, viene invece calcolata la standard deviation.

**Comment by UniprJRC** [comment]
Osservazione corretta. Bravo. Appena corretto sul sito di Giappichelli
