### ISSUE TITLE
errore pag 189 par. 5.5

### ISSUE THREAD

**Issue by erikadaloia** [UniprJRC/DSconMATLAB#161]
nell'esercizio 5.8 riga 5 c'è scritto 'FIDIST' invece che 'fitdist' cioè il vero nome della funzione

**Comment by UniprJRC** [comment]
MI raccomando di controllare la pagina di errata corrige prima di scrivere
![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/4a66c0cc-f175-49f3-94f2-85396e4ce2da)
