### ISSUE TITLE
errore che può ostacolare la compresione

### ISSUE THREAD

**Issue by Alematassa02** [UniprJRC/DSconMATLAB#162]
Salve Prof., 
 nell'esercizio HW 9.2 di pagina 336 viene chiesto di svolgere l'esercizio caricando in memoria il file "regionidemo.xlsx, questo file però non è presente nella cartella su matlab ma esiste il file chiamato "regioni.xlsx". Intuisco quindi che vi è stato uno sbaglio o nello scrivere il testo sul libro o nel denominare il file su matlab.
Ho provato, quindi, ad usare il file "regioni.xlsx" e ho notato che il range Q2:V22 (range proposto dal testo dell'esercizio) non va bene in quanto usandolo avrei tutti valori NAN,  il range che riporta i dati giusti della tabella è il range A1:E21. 

Spero di essere stata di aiuto.
Saluti

**Comment by UniprJRC** [comment]
Ha ragione. Grazie per la segnalazione.
Ho appena aggiunto il file regionidemo.xlsx. Faccia il pull e lo troverà nel capitolo sui grafici.
Lascio questo issue aperto ancora per qualche giorno
