### ISSUE TITLE
errore di battitura

### ISSUE THREAD

**Issue by martinamanca** [UniprJRC/DSconMATLAB#164]
Nell'esercizio 5.3, di pagina 172, riga 6, è stato indicato con "quan" il vettore che contiene le probabilità, mentre nella riga 7 il vettore è stato successivamente denominato "quant"

**Comment by UniprJRC** [comment]
Osservazione corretta inserita in errata corrige

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/1b01f1ef-8e74-4868-b964-d9d00bb8dbeb)
