### ISSUE TITLE
Errore di battitura pagina 293

### ISSUE THREAD

**Issue by matteocardi16** [UniprJRC/DSconMATLAB#168]
Alla riga 2 c'è un errore di battitura che non ostacola la comprensione relativo alla parola "crere": sostituire "crere" con "creare".

**Comment by UniprJRC** [comment]
Aggiunto in errata corrige
![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/15a19508-6f88-4482-a824-0d40c3f6fd21)
