### ISSUE TITLE
Errore di battitura pag 220

### ISSUE THREAD

**Issue by Vizzio98** [UniprJRC/DSconMATLAB#169]
Nell' esempio 6.3 vi manca una descrizione del procedimento all' intero del percorso.
Al numero 8 "% Calcolo del "

**Comment by UniprJRC** [comment]
Aggiunto in errata corrige

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/e7c96383-bb92-4459-864d-dbb5180f8c31)
