### ISSUE TITLE
errore ortografico

### ISSUE THREAD

**Issue by FBIANCHII** [UniprJRC/DSconMATLAB#17]
Alla pag.330 nel paragrafo di spiegazione della massimizzazione tra varianze y e Za: "Affinché l'arbitrarietà di a non alteri il problemi di massimizzazione" sarebbe corretto avere ""Affinché l'arbitrarietà di a non alteri il problema di massimizzazione".

**Comment by MarcoRianiUNIPR** [comment]
Grazie per la segnalazione

Aggiunto il suo nome alla pagina di errata corrige

p. 330 riga 9 partendo dal basso, rimpiazzare
...l'arbitrarietà di a non alteri il problemi di massimizzazione...
con
...l'arbitrarietà di a non alteri il problema di massimizzazione...
Segnalato da Alessandra Ramondetta e FBIANCHII.
