### ISSUE TITLE
Errore che ostacola la comprensione nell'esercizio 2.18 

### ISSUE THREAD

**Issue by antpci10** [UniprJRC/DSconMATLAB#173]
Nell'esercizio 2.18 che è in matlab nella cartella CapAlgebraBase in corrispondenza del file script matrici.m alla riga 118 del codice c'è un errore, in quanto viene scritto che un modo alternativo per generare i dati dalla distribuzione N(10,9) è: %X=normrnd(3,10,n,p), ma ciò è sbagliato perché la funzione di matlab normrnd vuole questa sintassi normrnd(mu,sigma), quindi il codice corretto da scrivere come alternativa è  %X=normrnd(10,3,n,p), poiché non bisogna invertire mu con sigma

**Comment by UniprJRC** [comment]
Alla riga 118 del file matrici.m io ho una cosa completamente diversa

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/923d555f-9353-482f-88fa-6307442699a7)

Può per favore controllare (QUESTO PER TUTTI) di avere fatti il pull con l'ultima versione dei file?

La cronologia di questo file in GitHub mi dice che le ultime due modifiche sono state fatte

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/da8a1077-872e-47c7-a70c-0b688631cfdc)

lo scorso 31 dicembre e il 23 settembre. In entrambi i casi io non ho trovato quello che lei dice di vedere alla riga 118.
Secondo me sta utilizzando un altro file modificato da qualcuno.

Mi faccia sapere.

**Comment by antoniapiaciliberti** [comment]
ho provveduto a fare il Pull  del file matrici.m, infatti l'errore segnalato da me prima è alla riga 206 e non più alla 118 del file matrici.m
grazie per la disponibilità.

**Comment by UniprJRC** [comment]
Ok ha ragione. La sua segnalazione è assolutamente corretta. Grazie per la segnalazione.
Il nuovo file è stato pushato sul server. Per favore faccia il pull e mi faccia sapere se ora è tutto a posto.
