### ISSUE TITLE
Errore nell'esercizio 3.8

### ISSUE THREAD

**Issue by antpci10** [UniprJRC/DSconMATLAB#175]
Al punto 2 dell'esercizio 3.8 viene richiesto di mostrare nella Command window le prime 6 colonne di XtabComplessiva, nel libro a pagina 119 alla riga 11 del codice c'è un errore poiché viene scritto disp(XtabComplessiva(:,1:7)), questo codice significa che devono essere mostrate le prime 7 colonne e non le prime 6 come richiesto dall'esercizio, per questo è opportuno sostituire il codice riportato nel libro con il seguente codice disp(XtabComplessiva(:,1:6))

**Comment by UniprJRC** [comment]
ANCORA UNA VOLTA. PER FAVORE CONTROLLI LA PAGINA DI ERRATA CORRIGE
PER FAVORE SIA IO SIA LEI PERDIAMO DEL TEMPO INUTILE. (LEI A SCRIVERE ED IO A RISPONDERE).

Questa segnalazione è apparsa in errata corrige il 27/09 

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/8e47b010-332b-4166-bcfa-db0e3d11e240)
