### ISSUE TITLE
Esercizio 7.1, errore di battitura

### ISSUE THREAD

**Issue by Dallo2001** [UniprJRC/DSconMATLAB#176]
Es. 7.1, pagina 228, ultima riga della consegna
Sostituire: **matrice di covarianze**
Con: **matrice delle correlazioni**

**Comment by UniprJRC** [comment]
Osservazione corretta.
Aggiunta in errata corrige

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/d41c24b4-b87f-42cf-98f3-4da6b5a26e84)
