### ISSUE TITLE
Errore ortografico 

### ISSUE THREAD

**Issue by FBIANCHII** [UniprJRC/DSconMATLAB#18]
Pag.331 prima frase "Tenendo presente che le colonna della matrice Z hanno somma..." sarebbe corretto avere "Tenendo presente che le **colonne** della matrice Z hanno somma..."

**Comment by MarcoRianiUNIPR** [comment]
Aggiunto il suo nome alla pagina di errata corrige. Grazie per la segnalazione

p. 331 riga 1, rimpiazzare
Tenendo presente che le colonna della matrice....
con
Tenendo presente che le colonne della matrice....
Segnalato da Nicole Tolve e FBIANCHII
