### ISSUE TITLE
Errore di battitura che non ostacola la comprensione

### ISSUE THREAD

**Issue by Dantenunes02** [UniprJRC/DSconMATLAB#181]
Pagina 98 es. 3.3 (Dante Nunes)
Riga 3 del codice del esercizio
Rimpiazzare:
Xtq è la table (107x4) riferita solo alle variabile quantitative
Con:
Xtq è la table (107x4) riferita solo alle variabil**i** quantitative

**Comment by UniprJRC** [comment]
Aggiunto in errata corrige grazie
![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/005dba57-40b5-4727-ba25-a0a8a15241d1)
