### ISSUE TITLE
errore codice 

### ISSUE THREAD

**Issue by marikap00** [UniprJRC/DSconMATLAB#187]
pag. 192, riga 8

(x.^2+y.^2-2 * rho * x. * y));
con
(x.^2+y.^2-2 * rho * x. * y);

**Comment by UniprJRC** [comment]
La seconda parentesi tonda è assolutamente necessaria in quanto la seconda parentesi chiude la parentesi che parte con exp(

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/94d14e5f-222e-4ff7-a29e-5e663a478c34)

Nello screenshot sopra, per favore noti il segno di _ sulle due parentesi per indicare il matching.

**Comment by marikap00** [comment]
ho segnalato l'errore perché matlab non mi fa girare il codice aggiungendo quella parentesi, mentre togliendola sì
allego immagine
![image](https://github.com/UniprJRC/DSconMATLAB/assets/146754754/98476c8e-35cc-4842-b986-e68349b11b3b)

**Comment by marikap00** [comment]
mi sono appena resa conto del mio errore, mi scusi prof! Avevo dimenticato il segno meno
Grazie mille!
