### ISSUE TITLE
Errore di battitura sul sito Giappichelli alla soluzione HW1.3

### ISSUE THREAD

**Issue by Vizzio98** [UniprJRC/DSconMATLAB#188]
Nella soluzione sul sito Giappichelli, alla soluzione dell' esercizio HW 1.3, vi è un errore di battiture al "disp" della trasformazione array in table con i nomi delle righe e delle colonne definiti come string array.
Alla riga 13 il disp dovrebbe essere - "disp(Mt)"

**Comment by UniprJRC** [comment]
Questa segnalazione non riesco proprio a capirla. 
Alla riga 13 c'è scritto disp(Mt) che produce

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/79869167-5c6a-444e-8b50-c24339957691)

Per ora questa segnalazione è etichettata come invalid a meno che non mi dimostri il contrario
