### ISSUE TITLE
Errore nella soluzione su Giappichelli HW 4.5

### ISSUE THREAD

**Issue by catalinagizzi** [UniprJRC/DSconMATLAB#192]
Nell'esercizio di riepilogo HW 4.5 a pagina viene richiesta la creazione di una timetable in cui le date sono riferite all'anno 2022. 
Nella soluzione su Giappichelli, nel secondo modo di risoluzione, viene inserito l'anno 2002.

**Comment by UniprJRC** [comment]
La sua segnalazione è corretta. Il nuovo file con la data corretta è stato caricato nel sito di Giappichelli.
