### ISSUE TITLE
HW 4.6 pagina 163

### ISSUE THREAD

**Issue by catalinagizzi** [UniprJRC/DSconMATLAB#195]
Nell'esercizio di riepilogo HW 4.6 viene richiesto di rappresentare la serie storica tramite la funzione stackedplot. Nella soluzione sul sito Giappichelli ho riscontrato la mancanza di tale richiesta.
In più nella riga 49 della soluzione bisogna sostituire head(RENDprice2ret) → head(RENDtick2ret)

**Comment by UniprJRC** [comment]
Entrambe le sue osservazioni sono corretto. Il file corretto è stato inserito nel sito di Giappichelli. Mi faccia sapere se ora è tutto a posto
