### ISSUE TITLE
errore che ostacola la comprensione Es HW9.5

### ISSUE THREAD

**Issue by Alematassa02** [UniprJRC/DSconMATLAB#201]
Salve, 
segnalo che nella soluzione dell'esercizio HW9.5 viene scritto "stima (parametrica) della densità " mentre poi viene calcolata la stima NON parametrica della densità (come anche viene richiesto dall'esercizio).

Saluti.

**Comment by UniprJRC** [comment]
La sua affermazione è assolutamente corretta. Bravo!!! 
Ho appena aggiunto nel sito di Giappichelli la versione corretta dell'esercizio HW9.5 con la stima non parametrica.
Questo mi da dato anche l'opportunità di aggiornare i commenti
