### ISSUE TITLE
chiarimento

### ISSUE THREAD

**Issue by FrancescaCapello** [UniprJRC/DSconMATLAB#220]
![image](https://github.com/UniprJRC/DSconMATLAB/assets/145284062/782029cc-e864-4ec8-ba11-d07013497232)
Buonasera, 
nella riga 13, c'è scritto "Primo tratto", non dovrebbe essere "secondo tratto" visto che i comandi successivi si riferiscono al secondo?
Grazie

**Comment by UniprJRC** [comment]
Certamente. File corretto
