### ISSUE TITLE
errore pagina 209

### ISSUE THREAD

**Issue by giusy927** [UniprJRC/DSconMATLAB#222]
inserire la virgola fra -20 e 80 quando viene citata la distribuzione uniforme "U(-20 80)"

**Comment by UniprJRC** [comment]
Aggiunto in errata corrige. Grazie per la segnalazione

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/a592b803-7c97-40b5-b490-2f31b196d6be)
