### ISSUE TITLE
Errore pagina 304

### ISSUE THREAD

**Issue by giusy927** [UniprJRC/DSconMATLAB#224]
Sostituire nella quarta riga della traccia dell'esercizio " Aggiungere il testo per indicare la posizione l'unità 43." con "Aggiungere il testo per indicare la posizione dell'unità 43"

**Comment by UniprJRC** [comment]
Aggiunto in errata corrige. Grazie.

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/a7d362e9-00d7-4e1f-935f-a1519a2faab2)
