### ISSUE TITLE
errore battitura che non ostacola la comprensione

### ISSUE THREAD

**Issue by marikap00** [UniprJRC/DSconMATLAB#225]
pagina 206, quartultima riga (prima dell'esercizio 6.1)

Le variabili rilevate sono: umidità in % (umidit), ceneri in % (ceneri) e tagliatelle rotte in %.
con
Le variabili rilevate sono: umidità in % (umidit), ceneri in % (ceneri) e tagliatelle rotte in % (rotte).

**Comment by UniprJRC** [comment]
Aggiunto in errata corrige

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/092f6a58-60e8-4dc7-9938-04b492ed2b13)
