### ISSUE TITLE
errore di battitura che può ostacolare la comprensione

### ISSUE THREAD

**Issue by FrancescaCapello** [UniprJRC/DSconMATLAB#226]
Nell'esercizio di riepilogo HW 5.7 c'è un errore nel codice del paragrafo: "Estrazione di un campione casuale dalla distribuzione W(1,1.5)"
Bisognerebbe sostituire questo:
![image](https://github.com/UniprJRC/DSconMATLAB/assets/145284062/24b9190d-b190-4c43-bb65-d13c6a102cac)
con questo:
![image](https://github.com/UniprJRC/DSconMATLAB/assets/145284062/b2a76371-b55c-4b15-aec9-744e244dae00)

**Comment by UniprJRC** [comment]
Questa segnalazione proprio non la capisco. Per ora la etichetto come "invalid" in attesa di ulteriori chiarimenti da parte sua. Non capisco proprio perché non vuole che venga inserita nel titolo il valore di n.

**Comment by FrancescaCapello** [comment]
Intendevo dire che il titolo sarebbe 'Campione casuale di numerosità dalla distribuzione n='. Inserendo il codice della prima immagine MATLAB mi segnala un errore perchè 'dalla distribuzione' andrebbe dopo la parola numerosità, non so se mi sono spiegata correttamente.

**Comment by FrancescaCapello** [comment]
mi scusi, avevo interpretato male io il comando! 'dalla distribuzione' pensavo fosse riferito al campione di numerosità n, invece è riferito al valore di n preso dalla distribuzione W, è corretto?

**Comment by UniprJRC** [comment]
il codice di cui sopra produce

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/a9612f68-a11f-4109-9436-2d6020920459)

Estraggo un campione di numerosità n=1000 dalla distribuzione W(1, 1.5) e rappresento graficamente la distribuzione di frequenze. Il valore di n non ha niente a che vedere con W(1, 1.5) ma è solo riferito al numero di osservazioni estratte dalla distribuzione  W(1, 1.5)
