### ISSUE TITLE
Errore esercizio 14.12 pagina 564

### ISSUE THREAD

**Issue by giorgialusardi** [UniprJRC/DSconMATLAB#229]
Nell'ultima frase nel testo dell'esercizio 14.12
sostituire "pu**o** essere..."
con "pu**ò** essere..."

**Comment by UniprJRC** [comment]
Aggiunto in errata corrige, Grazie per la segnalazione

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/f4961a43-cdea-40fc-a27f-128b5cb4552d)
