### ISSUE TITLE
errore di battitura che non ostacola la comprensione

### ISSUE THREAD

**Issue by AntonioSciaraffia** [UniprJRC/DSconMATLAB#234]
Pag. 172 es. 5.2
Alla riga 6 , nel commento è stato scritto quan invece di quant
Saluti

**Comment by UniprJRC** [comment]
Mi raccomando prima di scrivere di controllare la pagina di errata corrige
![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/8fa56d6b-d8df-483e-a500-37947212cb97)
