### ISSUE TITLE
errore pag 85 

### ISSUE THREAD

**Issue by benedetta29** [UniprJRC/DSconMATLAB#244]
nelle ultime 3 righe.." se x è un vettore RIGA" al posto di colonna a pag.85 capitolo 2.

**Comment by UniprJRC** [comment]
Questo non è un errore

x= vettore colonna di lunghezza n è definito da

x=x_1
    x_2
   ....
   x_n

y vettore colonna di lunghezza p è definito da 

y=y_1
    y_2
   ....
   y_p

x+y' = x_1   +  ( y_1 y_2 ... y_p)
          x_2
           ....
           x_n

La somma di questi due vettore (il primo colonna x) ed il seconda riga (poiché c'è il segno di traposto su y, ossia y') produce la matrice di dimensione n x p dell'equazione (2.4)

Il generico elemento di questa matrice è x_i+y_j   
i=1, 2, ..., n
j=1, 2, ..., p

Mi faccia sapere se sono stato chiaro

**Comment by benedetta29** [comment]
sisi ora è chiaro. grazie
