### ISSUE TITLE
errore di battitura pagina 315

### ISSUE THREAD

**Issue by federico-baio** [UniprJRC/DSconMATLAB#246]
Nel testo dell'esercizio 9.19, nella sesta riga manca un apostrofo: c'è scritto "...sull asse x..." invece di "...sull'asse x..."

**Comment by UniprJRC** [comment]
Fatto grazie

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/dfc24bc9-72d8-43ee-943d-4b11ba2f2915)
