### ISSUE TITLE
errore pagina 319

### ISSUE THREAD

**Issue by federico-baio** [UniprJRC/DSconMATLAB#247]
La penultima riga di pagina 319 riporta l'analisi degli istogrammi univariati in riferimento alla figura 9.24 invece che in riferimento alla figura 9.23. È infatti la figura 9.23 che riporta sulla diagonale principale gli istogrammi univariati, mentre la figura 9.24 riporta sulla diagonale principale i box plot.

**Comment by UniprJRC** [comment]
Fatto grazie

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/d227d917-ba89-43eb-888d-23f25ff17c95)
