### ISSUE TITLE
esercizio 10.1 pagina 341-342

### ISSUE THREAD

**Issue by federico-baio** [UniprJRC/DSconMATLAB#253]
Nel primo punto del testo dell'esercizio chiede di dimostrare che la norma al quadrato di ogni colonna della matrice degli scostamenti dalla media divisa per la radice di n-1 è uguale alla varianza campionaria delle variabili originarie. 
Teoricamente, essendo la norma al quadrato pari alla sommatoria degli scostamenti al quadrato dalla media, ed essendo questa sommatoria il numeratore nella formula della varianza; per ottenere la varianza non si dovrebbe dividere la norma al quadrato per n-1 (ossia per il denominatore della formula della varianza campionaria) invece di dividerla per la radice quadrata di n-1?

**Comment by UniprJRC** [comment]
Assolutamente corretto. Bravo.
Aggiunto in errata corrige

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/837226ee-c558-4e3b-9bf9-e07095491f95)

**Comment by federico-baio** [comment]
Scusi prof, ma io sono Federico Baio non Dallo2001.
