### ISSUE TITLE
errore pag.108

### ISSUE THREAD

**Issue by gaiacordella** [UniprJRC/DSconMATLAB#254]
nel paragrafo dopo la parentesi viene messo un punto e subito dopo la lettera minuscola, 
(-2,0]. mostrare le prime 5 righe del vettore... 
da correggere con 
(-2,0]. Mostrare le prime 5 righe del vettore...

**Comment by UniprJRC** [comment]
Fatto grazie

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/d8b93618-cbf4-4a50-a24e-f1ff1242a572)
