### ISSUE TITLE
Errore pagina 398

### ISSUE THREAD

**Issue by lorenzalamanda** [UniprJRC/DSconMATLAB#258]
Nella pagina 398 c'è un errore nella formula: j=1 ripetuto due volte, dovrebbe essere s=1

**Comment by UniprJRC** [comment]
Segnalazione corretta.
Fatto grazie

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/ab60c83b-3b27-4bce-96a3-860e82428d08)
