### ISSUE TITLE
Pagina 281, esercizio HW 8.3

### ISSUE THREAD

**Issue by federico-baio** [UniprJRC/DSconMATLAB#263]
Nella prima riga del testo dell'esercizio a pagina 281 va aggiunta la parola prestiti:
"Ad esempio X1 riporta il numero di **prestiti** personali per ogni cliente della banca..."

**Comment by UniprJRC** [comment]
Fatto grazie
![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/5b99a8a6-1770-4e68-8b93-aea14af65e41)
