### ISSUE TITLE
Pagina 281, esercizio HW 8.5

### ISSUE THREAD

**Issue by federico-baio** [UniprJRC/DSconMATLAB#264]
L'esercizio HW 8.5 chiede di calcolare l'indice gamma utilizzando per le righe la posizione occupata all'interno dell'azienda (da Junior Employee a Senior Manager) e per le colonne il grado di dipendenza rispetto alle sigarette (da none a heavy). La soluzione su Giappichelli nella quale viene creata la tabella pivot, invece, riporta sulle righe il grado di dipendenza e sulle colonne la posizione occupata. Essendo l'indice gamma un indice simmetrico il valore non cambia anche trasponendo la tabella di partenza, ma mi sembrava giusto segnalarlo comunque.

**Comment by UniprJRC** [comment]
Come hai scritto l'indice gamma è simmetrico di conseguenza i risultati non cambiano. Tuttavia dato che nel testo c'è scritto di inserire sulle righe la posizione occupata, si deve inserire sulle righe la posizione occupata. Ho aggiornato il file
