### ISSUE TITLE
errore pag.302

### ISSUE THREAD

**Issue by AntonioSciaraffia** [UniprJRC/DSconMATLAB#265]
Nella spiegazione del libro (Osservazione : ... ) si parla di una table di dimensione 60x5 sebbene di seguito venga riportata una porzione di una table 60x4

**Comment by UniprJRC** [comment]
L'osservazione è corretta. fitlm riporta una struct con il field Residuals con 4 colonne e non con 5. Bravo, segnalazione aggiunta in errata corrige.

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/c0f98b8c-79ea-4022-8a93-3b27b2dd9794)
