### ISSUE TITLE
Errore di battitura pag. 666

### ISSUE THREAD

**Issue by AntonioSciaraffia** [UniprJRC/DSconMATLAB#266]
In legenda è stato scritto "v rePisioni" invece di "Previsioni"

**Comment by UniprJRC** [comment]
Non capisco a p. 266 c'è scritto nella legenda

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/87555ce3-117c-46e3-81f8-137579758add)

**Comment by AntonioSciaraffia** [comment]
Allego la foto della pagina 666 sul libro
![I2023-11-10 ore 17 49 07_69876125](https://github.com/UniprJRC/DSconMATLAB/assets/147667932/a1bf77b1-abe0-4839-bfd9-d5a060a4579a)

**Comment by UniprJRC** [comment]
Adesso sono all'estero e non ho con me la versione cartacea, Domani torno in Italia e controllo cosa c'è nella mai versione. In ogni caso, nella sua versione in stampa non ci sono dubbi

**Comment by UniprJRC** [comment]
Quest'errore è veramente misterioso ed è dovuto al processo di stampa. In ogni caso, inserito in errata corrige. Grazie per la segnalazione.
