### ISSUE TITLE
Errore ortografico

### ISSUE THREAD

**Issue by ElisaRenna** [UniprJRC/DSconMATLAB#27]
Pagina 129 riga 32

sostituire
% Fisso un seed per la **replicatibilità** dei risultati

con 
% Fisso un seed per la **replicabilità** dei risultati

**Comment by MarcoRianiUNIPR** [comment]
Aggiunto in errata corrige. Grazie per la segnalazione

p. 129, riga 32 del codice. Rimpiazzare
% Fisso un seed per la replicatibilità dei risultati
con
% Fisso un seed per la replicabilità dei risultati
Segnalato da Elisa Renna
