### ISSUE TITLE
errore di battitura, pagina 407

### ISSUE THREAD

**Issue by federico-baio** [UniprJRC/DSconMATLAB#272]
Alla fine della quarta riga a pagina 407 va sostituito:
...rispetto ad un'atra coppia.
con
...rispetto ad un'a**l**tra coppia.

**Comment by UniprJRC** [comment]
Fatto grazie
![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/968b67ba-e6e5-41e8-9163-be85d0094617)
