### ISSUE TITLE
Pagina 417, HW 11.5

### ISSUE THREAD

**Issue by federico-baio** [UniprJRC/DSconMATLAB#273]
Nel testo dell'esercizio HW 11.5, viene chiesto di creare una matrice 3x10  dalla distribuzione Binomiale con parametri (n,π)=(10,0.3) e di calcolare la matrice degli indici di Jaccard tra le righe di questa matrice. 

Teoricamente, essendo che l'indice di similarità di Jaccard viene usato tra variabili dicotomiche, i parametri corretti della distribuzione binomiale, non dovrebbero essere: (n,π)=(1,0.3)?

Anche sulla soluzione sul sito di Giappichelli la distribuzione ha come valore di n, n=1 e non n=10 :
_X=binornd(1,0.3,3,10);_

**Comment by UniprJRC** [comment]
Confermo che l'esercizio è risolto correttamente che attendevamo che qualcuno segnalasse questo refuso

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/bac15de7-040f-45a4-97a4-0921f1f98a8d)
