### ISSUE TITLE
errore pagina 322 esercizio 9.20

### ISSUE THREAD

**Issue by AntonioSciaraffia** [UniprJRC/DSconMATLAB#280]
Nel testo dell' esercizio  è stato scritto "aggiungere i contorni non parametri" invece di "contorni non parametriCI".
Saluti.

**Comment by UniprJRC** [comment]
Fatto grazie

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/b0c4b960-63b5-4e31-8fd9-70297c311652)
