### ISSUE TITLE
Errore di battitura

### ISSUE THREAD

**Issue by AntonioSciaraffia** [UniprJRC/DSconMATLAB#285]
Pagina 492
Riga 10 dopo l'elenco numerato
Sostituire "in cui coppie di fenomeni sono statI classificatI" con "coppie di fenomeni sono statE classificatE"

**Comment by UniprJRC** [comment]
Fatto grazie

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/2d754147-8a18-4685-b765-160541a5756d)
