### ISSUE TITLE
Errore pagina 458

### ISSUE THREAD

**Issue by ElenaMarongiu** [UniprJRC/DSconMATLAB#286]
Nel codice a pagina 458
sostituire: 
text(Y(:,1),Y(:,2),Xtable.Properties.RowNames)
con
text(Yst(:,1),Yst(:,2),Xtable.Properties.RowNames)
dato che: plot(Yst(:,1),Yst(:,2),'o')

**Comment by UniprJRC** [comment]
Brava. Segnalazione assolutamente corretta.

Nei file di corredo al libro il codice era scritto correttamente ma nel libro è stato riportato sbagliato.

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/51a21ac4-2964-4c73-b6af-052a4aae11f9)
