### ISSUE TITLE
Giappichelli HW 12.3

### ISSUE THREAD

**Issue by federico-baio** [UniprJRC/DSconMATLAB#289]
Nella soluzione su Giappichelli dell'esercizio HW 12.3, nella section in cui vengono calcolati i componenti principali; il secondo `disp` riporta la frase: 
_'Analisi delle correlazioni tra la prima PC e le variabili originarie'_
invece di
_'Analisi delle correlazioni tra la seconda PC e le variabili originarie'_

**Comment by UniprJRC** [comment]
Fatto grazie
