### ISSUE TITLE
ESERCIZIO di riepilogo HW 5.5

### ISSUE THREAD

**Issue by FrancescaPiaSarno** [UniprJRC/DSconMATLAB#291]
Parte della soluzione (presente sul sito Giappichelli) dell'esercizio di riepilogo HW 5.5 di pagina 200 del libro è errata.
Io noto che i dati della numerosità campionaria anzichè essere: nn=[100, 500, 5000, 20000, 50000] dovrebbero essere **nn=[100, 500, 5000, 20000, 100000]** come riportato tra i dati dell’esercizio.
 
Francesca Pia Sarno

**Comment by UniprJRC** [comment]
Corretto grazie.
Solo una puntualizzazione
nn deve essere
nn=[100, 500, 5000, 20000, 50000, 100000]
e non come scrive
nn=[100, 500, 5000, 20000, 100000]
