### ISSUE TITLE
Pagina 508, output esercizio 13.3

### ISSUE THREAD

**Issue by federico-baio** [UniprJRC/DSconMATLAB#292]
A pagina 508 è indicato quello che dovrebbe essere l'output della prima parte del codice dell'esercizio 13.3, ossia la tabella _InertiaExplainedtable_; ma in realtà nel codice riportato sopra, manca un `disp` per visualizzare quella table nella command window.

**Comment by UniprJRC** [comment]
Fatto grazie

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/d83f96d0-ba43-4602-97a0-af1cbe14dccd)
