### ISSUE TITLE
2 errori sito Giappichelli

### ISSUE THREAD

**Issue by giorgialusardi** [UniprJRC/DSconMATLAB#293]
Sito Giappichelli, esercizio 9.5
Alla riga 15 sostituire "...**le** variabile..." con "...**la** variabile..."
Alla riga 22 sostituire "...quelle false **potrebbe** essere..." con "...quelle false **potrebbero** essere..."

**Comment by UniprJRC** [comment]
Sito di Giappichelli aggiornato. Grazie per la segnalazione
