### ISSUE TITLE
Giappichelli, esercizio HW 13.1

### ISSUE THREAD

**Issue by federico-baio** [UniprJRC/DSconMATLAB#294]
L'esercizio HW 13.1 chiede di utilizzare i dati dell'esercizio di riepilogo 8.2; ma la tabella di contingenza N riportata nella soluzione dell'esercizio HW 13.1 su Giappichelli, riporta nella posizione 2,2 il valore _63_ invece di _61_

Oltretutto, i nomi delle variabili sono scritti nell'ordine sbagliato. Infatti la tabella di contingenza originale dell'esercizio HW 8.2 ha come variabili: no, forse, si. Nella soluzione dell'esercizio HW 13.1 però, le variabili sono scritte nel seguente ordine: si, forse, no; creando di fatto una tabella di contingenza diversa.

<img width="318" alt="Screenshot 2023-11-22 alle 11 48 11" src="https://github.com/UniprJRC/DSconMATLAB/assets/145587337/dfcdc374-5876-457a-a9ac-41ecdac7f4b0">
<img width="318" alt="Screenshot 2023-11-22 alle 11 48 29" src="https://github.com/UniprJRC/DSconMATLAB/assets/145587337/4568f1aa-9962-4ccd-81e8-3ea089b44bda">

Proprio per questo l'interpretazione del grafico di analisi delle corrispondenze su Giappichelli afferma che _Il farmaco A è più legato a sì e quello più più legato a no, ed il farmaco C è legato a forse_, quando teoricamente l'interpretazione corretta non dovrebbe essere che _il farmaco A è quello più legato al "no", mentre quello più legato al "si" è il farmaco C, e invece il farmaco B è legato al "forse"_? (allego foto del grafico di analisi delle corrispondenze che è uscito a me)

<img width="693" alt="Screenshot 2023-11-22 alle 11 57 05" src="https://github.com/UniprJRC/DSconMATLAB/assets/145587337/a71f4b50-52f7-455c-a549-efa9f781a4c7">

**Comment by UniprJRC** [comment]
Tutti gli esercizi del capitolo 13 sono stati rivisti ed inseriti con la corretta colorazione. In ogni caso le segnalazioni che avevi fatto erano corrette
