### ISSUE TITLE
File Giappichelli HW 13.2

### ISSUE THREAD

**Issue by federico-baio** [UniprJRC/DSconMATLAB#295]
Il file mlx caricato su Giappichelli come soluzione dell'esercizio HW 13.2 non presenta l'analisi delle corrispondenze della tabella 13.2 (ossia della tabella di contingenza tra grado di istruzione e professione lavorativa) come richiesto dal testo dell'esercizio, ma presenta l'analisi delle corrispondenze di un'altra tabella, che invece mette in relazione il tipo di acquisto con la professione.

**Comment by UniprJRC** [comment]
File aggiornato nel sito di Giappichelli
