### ISSUE TITLE
2 errori Giappichelli, HW 12.3

### ISSUE THREAD

**Issue by giorgialusardi** [UniprJRC/DSconMATLAB#301]
Nella riga 23 sostituire "...è funzione **crescete**..." con "...è funzione **crescente**..."
Nella riga 35 sostituire "...della seconda **componenti** principale..." con "...della seconda **componente** principale..."

**Comment by UniprJRC** [comment]
Fatto, per favore controlli e mi faccia sapere

**Comment by giorgialusardi** [comment]
Ora li vedo corretti, grazie

**Comment by UniprJRC** [comment]
Grazie a lei per le segnalazioni
