### ISSUE TITLE
Errore esercizi di fine capitolo 8.2

### ISSUE THREAD

**Issue by lorenzalamanda** [UniprJRC/DSconMATLAB#303]
Nell'esercizio di fine capitolo 8.2 errore sull'osservazione riguardante l'indice GKlambdayx bisogna correggere sostituendo con: l'indice è uguale 0 quando tutte le frequenze massime di riga giacciono nella stessa colonna.

**Comment by UniprJRC** [comment]
Non capisco, nel sito di Giappichelli c'è scritto esattamente quello che lei dice
