### ISSUE TITLE
errori che ostacolano la comprensione.   pag 148

### ISSUE THREAD

**Issue by cesarezolesi** [UniprJRC/DSconMATLAB#306]
Sopra TT.properties.rowtimes viene menzionata "mentre nella table i nomi delle righe si chiamavano rownames , nella table abbiamo la proprietà rowtimes"
bisognerebbe sostituire seconda table con TimeTable.
Cordiali saluti.

**Comment by UniprJRC** [comment]
Fatto grazie

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/be79462d-5a09-4297-bf55-26321745c4f9)
