### ISSUE TITLE
errore in Errata_Corrige

### ISSUE THREAD

**Issue by marikap00** [UniprJRC/DSconMATLAB#317]
tra gli errori di battitura che non ostacolano la comprensione, quello segnalato a pag. 310 si trova in realtà a pag. 319

**Comment by UniprJRC** [comment]
Brava fatto.
Solo per dire che appezziamo molto la dedizione con cui sta leggendo il libro. 

![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/9d401183-baa6-49c2-90dc-ef4699a37346)
