### ISSUE TITLE
Source Control > Pull error

### ISSUE THREAD

**Issue by teo2600** [UniprJRC/DSconMATLAB#331]
Utilizzando MATLAB 2023b via web browser, quando cerco di aggiornare la libreria DSconMATLAB (originariamente caricata con il comando "!git clone https://github.com/UniprJRC/DSconMATLAB") attraverso la voce di menu "Source Control > Pull", continuo ad ottenere l'errore:

Pull Changes
Unable to fetch from the remote "origin" at https://github.com/UniprJRC/DSconMATLAB.git.
object not found - no match for id (5c39762a248ce786d19265f57f527dc9b9938b6c) (-3x9)

**Comment by UniprJRC** [comment]
Ho controllato e nel mio caso ha scaricato tutto senza problemi
![image](https://github.com/UniprJRC/DSconMATLAB/assets/55737234/5d100a76-b157-4d8d-acc9-59b387a707d0)

Magari è stato un problema momentaneo di rete. Potrebbe per favore riprovare e farci sapere?

**Comment by teo2600** [comment]
![screen2](https://github.com/UniprJRC/DSconMATLAB/assets/12600333/8a2f5922-4faf-4f7b-bb14-b95189ede304)
![screen1](https://github.com/UniprJRC/DSconMATLAB/assets/12600333/c46de471-51b0-4354-827b-e4106f1402c9)

Ho provato più e più volte, e in giornate diverse.

Ho anche eliminato la repository e ricaricata nuovamente, ma ottengo sempre lo stesso errore.

Se può servire, uso un sistema operativo Lubuntu:
Linux lulin 6.5.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

E uso il web browser Chrome:
Versione 123.0.6312.58 (Build ufficiale) (a 64 bit)

Grazie.

**Comment by AldoCorbelliniUNIPR** [comment]
Buonasera,

Vedo che sta usando un sistema abbastanza peculiare, ma, casualmente ho appena installato anche un sistema Lubuntu per fare dei test con MATLAB, provo a replicare il problema con il mio setup e le faccio sapere.

Cordiali saluti
Aldo Corbellini


__________________________________________
Aldo Corbellini, PhD,
Associate Professor of Economic Statistics,
Department of Economics and Management,
University of Parma
Via Kennedy, 6 Parma, Italy.



Da: teo2600 ***@***.***>
Inviato: mercoledì 20 marzo 2024 16:53
A: UniprJRC/DSconMATLAB ***@***.***>
Cc: Subscribed ***@***.***>
Oggetto: Re: [UniprJRC/DSconMATLAB] Source Control > Pull error (Issue #331)


screen2.jpg (view on web)<https://github.com/UniprJRC/DSconMATLAB/assets/12600333/8a2f5922-4faf-4f7b-bb14-b95189ede304>
screen1.jpg (view on web)<https://github.com/UniprJRC/DSconMATLAB/assets/12600333/c46de471-51b0-4354-827b-e4106f1402c9>

Ho provato più e più volte, e in giornate diverse.

Ho anche eliminato la repository e ricaricata nuovamente, ma ottengo sempre lo stesso errore.

Se può servire, uso un sistema operativo Lubuntu:
Linux lulin 6.5.0-26-generic #26<https://github.com/UniprJRC/DSconMATLAB/issues/26>~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

E uso il web browser Chrome:
Versione 123.0.6312.58 (Build ufficiale) (a 64 bit)

Grazie.

-

**Comment by AldoCorbelliniUNIPR** [comment]
> Utilizzando MATLAB 2023b via web browser, quando cerco di aggiornare la libreria DSconMATLAB (originariamente caricata con il comando "!git clone https://github.com/UniprJRC/DSconMATLAB") attraverso la voce di menu "Source Control > Pull", continuo ad ottenere l'errore:
> 
> Pull Changes Unable to fetch from the remote "origin" at https://github.com/UniprJRC/DSconMATLAB.git. object not found - no match for id ([5c39762](https://github.com/UniprJRC/DSconMATLAB/commit/5c39762a248ce786d19265f57f527dc9b9938b6c)) (-3x9)

**Comment by teo2600** [comment]
Grazie mille!

**Comment by UniprJRC** [comment]
Solo per sapere se il problema è stato risolto oppure è ancora presente?

**Comment by MarcoRianiUNIPR** [comment]
Problema risolto

**Comment by teo2600** [comment]
Grazie mille.

Cordiali saluti.

Matteo Abbia

Il gio 12 set 2024, 11:48 Marco Riani ***@***.***> ha scritto:
