### ISSUE TITLE
Errore di comunicazione nella registrazione alla biblioteca digitale 

### ISSUE THREAD

**Issue by giorgiapignoli** [UniprJRC/DSconMATLAB#344]
Segnalo che al momento risulta impossibile effettuare la registrazione alla biblioteca digitale di Giappichelli per accedere ai file forniti. Una volta inseriti tutti i dati necessari, cliccando su "Registra", appare una finestra con scritto "si è verificato un errore di comunicazione" (anche utilizzando dispositivi diversi). E' possibile accedervi in altro modo?

**Comment by MarcoRianiUNIPR** [comment]
Su questo aspetto occorre contattare direttamente Giappichelli. Lascio aperto l'issue per capire se il problema è stato risolto. Invito altri studenti a comunicare se hanno avuto (stanno avendo) lo stesso problema

**Comment by MarcoRianiUNIPR** [comment]
Chiudo l'issue dato che non c'è stato seguito e nessun altro ha segnalato problemi
