### ISSUE TITLE
Errore di battitura nel Materiale supplementare al Capitolo 1 

### ISSUE THREAD

**Issue by Francesco-Rinaudo** [UniprJRC/DSconMATLAB#345]
Segnalo un errore di battitura nel Materiale supplementare del Capitolo 1, pag 9, penultimo paragrafo. Vi è un errore di battitura nella parola Window. Anziché scritta come quest'ultima è digitata nel seguente modo "WIndow".
<img width="1256" alt="Screenshot 2024-09-20 alle 00 22 47" src="https://github.com/user-attachments/assets/30cbb588-607a-464e-88fe-01c54e8f8219">

**Comment by MarcoRianiUNIPR** [comment]
Segnalazione corretta 1/3 di punto. La correzione viene fatta intorno alle ore 17.00

**Comment by MarcoRianiUNIPR** [comment]
La correzione è stata effettuata.
