### ISSUE TITLE
Errore di scelta della matrice da calcolare

### ISSUE THREAD

**Issue by filippodilieto** [UniprJRC/DSconMATLAB#346]
Segnalo un errore nelle soluzioni degli esercizi supplementari, pagina 15. Viene calcolato il seno della matrice M invece della matrice MA, come richiesto nell'esercizio.
<img width="699" alt="Screenshot 2024-09-21 alle 09 19 27" src="https://github.com/user-attachments/assets/78c833d9-815a-43bb-adec-589948f9e75c">

**Comment by MarcoRianiUNIPR** [comment]
Osservazione corretta.

Ho corretto il testo dell'esercizio chiedendo di applicare il seno a tutti gli elementi delle matrice `M`
![image](https://github.com/user-attachments/assets/59682ff8-abda-4834-aa53-c44e6d65780c).
Ora correggo il file sul sito di Giappichelli

**Comment by MarcoRianiUNIPR** [comment]
Correzione fatta nel sito di Giappichelli. Mi faccia sapere se ora è tutto a posto

**Comment by filippodilieto** [comment]
Ora è corretto.
