### ISSUE TITLE
Errore di denominazione di una variabile 

### ISSUE THREAD

**Issue by alessiagrandi** [UniprJRC/DSconMATLAB#352]
A pagina 49, esercizio 1.7 nel punto 1 all'interno della parentesi la variabile viene chiamata RowNames anziché ReadRowNames

**Comment by MarcoRianiUNIPR** [comment]
Brava. Questa è una segnalazione da un punto!. 

![image](https://github.com/user-attachments/assets/7b9dfcc7-df61-40bc-97b3-bf160d2e4025)
