### ISSUE TITLE
errore di battitura che non ostacola la comprensione

### ISSUE THREAD

**Issue by Anastasia2904** [UniprJRC/DSconMATLAB#360]
Esercitazione CharStringheTable
''Creare lo string **arrary** di seguito e denominarlo Mio''

**Comment by MarcoRianiUNIPR** [comment]
Segnalazione assolutamente corretta. Aspetto a modificare il file nel sito di Giappichelli in attesa di segnalazioni di altri refusi

**Comment by MarcoRianiUNIPR** [comment]
Corretto nel sito di Giappichelli
