### ISSUE TITLE
Errore di ortografia che non ostacola la comprensione 

### ISSUE THREAD

**Issue by Anastasia2904** [UniprJRC/DSconMATLAB#362]
Nell’esercitazione di base al capitolo 1 : “introduzione all’utilizzo di Matlab e alla gestione dei dati”, a pag. 12 “tramite l’istruzione who mostrare tutte le variabili attualmente **presente** nel Workspace”

**Comment by MarcoRianiUNIPR** [comment]
Osservazione corretta.
Aspetto a fare l'aggiornamento nel sito di Giappichelli nel caso vengano trovati altri refusi. Di conseguenza l'issue per ora rimane aperto

**Comment by MarcoRianiUNIPR** [comment]
Corretto nel sito di Giappichelli
