### ISSUE TITLE
Errore di battitura

### ISSUE THREAD

**Issue by filippodilieto** [UniprJRC/DSconMATLAB#364]
<img width="731" alt="Screenshot 2024-09-29 alle 12 32 27" src="https://github.com/user-attachments/assets/e370ff19-02f8-4561-8f9c-2b11d5a06ac8">

Pagina 7, file di soluzione di CharStringheTable. La consegna dell'esercizio ci chiede di estrarre fino alla riga 13. Nel commento viene scritto di estrarre fino alla riga 11.

**Comment by MarcoRianiUNIPR** [comment]
Osservazione corretta. Lascio aperto l'issue in quanto la correzione nel sito di Giappichelli viene fatta lun 30 settembre nel pomeriggio

**Comment by MarcoRianiUNIPR** [comment]
Corretto nel sito di Giappichelli
