### ISSUE TITLE
Errore nel calcolo della mediana

### ISSUE THREAD

**Issue by filippodilieto** [UniprJRC/DSconMATLAB#369]
<img width="634" alt="Screenshot 2024-10-01 alle 13 59 52" src="https://github.com/user-attachments/assets/fce1a0f7-0d7f-4418-a924-8f0c5198d450">

Pagina 2, la consegna era la seguente:"Creare la tabella pivot delle mediane delle retribuzione per ciascun livello di Gender e Education...", tuttavia nell'output viene calcolata la somma.

**Comment by MarcoRianiUNIPR** [comment]
sì sì mi è già stato fatto notare. Lo correggo entro la fine della giornata
