### ISSUE TITLE
Errore di battitura nel file esercitazione Base

### ISSUE THREAD

**Issue by alessiagrandi** [UniprJRC/DSconMATLAB#370]
A pagina 10 del file esercitazione Base, nel secondo punto dove dice "Estrarre gli elementi in posizione dispari del vettore MA e mostrarli nella Command Window". Il vettore è MAvec e non MA (come dimostrato dal file BASEOUT)

**Comment by MarcoRianiUNIPR** [comment]
Corretto nel sito di Giappichelli
![image](https://github.com/user-attachments/assets/1eba7e4d-2449-47cf-a60d-af05c5722c04)
Grazie per la segnalazione
