### ISSUE TITLE
Errore di battitura che non ne ostacola la comprensione 

### ISSUE THREAD

**Issue by CorinneCasalini** [UniprJRC/DSconMATLAB#371]
A pagina 311, penultima riga "**solo** le 3 regioni con i valori..." anziché "**sono** le 3 regioni con i valori..."
[Analisi pag.311.pdf](https://github.com/user-attachments/files/17213091/Analisi.pag.311.pdf)

**Comment by MarcoRianiUNIPR** [comment]
Fatto grazie
![image](https://github.com/user-attachments/assets/dcdefe78-b483-4e2c-bc5c-cb8f2ca4c70e)
