### ISSUE TITLE
Errore battitura in OperazioniMatriciOut 

### ISSUE THREAD

**Issue by leonardospinetti** [UniprJRC/DSconMATLAB#372]
Alla terza pagina, nel controllo dell'uguaglianza delle implementazioni, per ProfileCols anziché "profili colonna" è stato scritto "profili riga".
<img width="1020" alt="Screenshot 2024-10-01 at 10 17 24 PM" src="https://github.com/user-attachments/assets/7c2faafb-97e0-4998-aa7b-5014aa8234f5">

**Comment by MarcoRianiUNIPR** [comment]
La ringrazio per la senalazione. Il file è stato corretto nel sito web di Giappichelli
