### ISSUE TITLE
errore di battitura che non ostacola la comprensione

### ISSUE THREAD

**Issue by rossigiacomo47** [UniprJRC/DSconMATLAB#373]
Segnalo un errore di battitura che non ostacola la comprensione sulla pagina web di analisi dei dati per il marketing, nel titolo della sezione "argomenti da trattare nelle varie settimane (a.a. 2024/2025)", dove "varie" è scritto erroneamente come "vare"

(nonostante l'errore non sia nel libro, ho ugualmente ritenuto potesse essere utile la sua segnalazione)

allego screenshot
<img width="1440" alt="Screenshot 2024-10-02 alle 10 49 39" src="https://github.com/user-attachments/assets/db691631-0865-44b7-bfd1-0982bc1e6e07">

**Comment by MarcoRianiUNIPR** [comment]
Corretto grazie
