### ISSUE TITLE
Errore di battitura in TabellePivot

### ISSUE THREAD

**Issue by leonardospinetti** [UniprJRC/DSconMATLAB#374]
Pagina 3, anziché "periodicità" è stato scritto "periodicitò".
<img width="1020" alt="Screenshot 2024-10-02 at 11 19 22 AM" src="https://github.com/user-attachments/assets/79fecd79-b5bb-4b38-837d-8ce5e5a97e18">

**Comment by MarcoRianiUNIPR** [comment]
OK grazie. Aspetto a fare la correzione nel sito di Giappichelli per capire se ci sono altri refusi

**Comment by MarcoRianiUNIPR** [comment]
Sito Giappichelli aggiornato
