### ISSUE TITLE
Scambio di dizione tra "Ultime 10 righe" e "Prime 10 righe" nel file OperazioniMatriciOut.pdf (slide 5 in alto)

### ISSUE THREAD

**Issue by Benedetto0301** [UniprJRC/DSconMATLAB#388]
![WhatsApp Image 2024-10-03 at 09 09 20](https://github.com/user-attachments/assets/5cb8d9c0-9bce-4d5a-a367-13cae922ffca)

Il testo chiede di figurare nella command window le ultime 10 righe della table dei profili colonna; ma quando scrive il codice inserisce "disp('Prime 10 righe della table dei profili colonna')" piuttosto che "disp('Ultime 10 righe della table dei profili colonna')"

Nella segnalazione uso le virgolette alte per denotare la parte in questione a cui mi riferisco. In allegato l'immagine dell'oggetto della mia segnalazione.

**Comment by MarcoRianiUNIPR** [comment]
Osservazione corretta. Bravo
Attendo a fare la correzione nel caso in cui ci fossero altri refusi

**Comment by MarcoRianiUNIPR** [comment]
File aggiornato nel sito di Giappichelli. Per favore controlli che ora sia tutto a posto
