### ISSUE TITLE
Errore di battitura nel file "Analisi esplorative.pdf" 

### ISSUE THREAD

**Issue by Benedetto0301** [UniprJRC/DSconMATLAB#396]
![WhatsApp Image 2024-10-04 at 11 16 07](https://github.com/user-attachments/assets/dd5c0354-c5a6-4fdb-b7ef-95f60d1132b2)

Segnalo che nella pagina 1 in basso c'è un errore di battitura poichè al posto di "versione" c'è scritto "versioned".

**Comment by MarcoRianiUNIPR** [comment]
osservazione corretta. Stasera viene corretta nel sito di Giappichelli

Grazie per la segnalazione

**Comment by MarcoRianiUNIPR** [comment]
File corretto nel sito di Giappichelli. Per favore controlli che ora sia tutto a posto
