### ISSUE TITLE
Errore di battitura che non ostacola la comprensione

### ISSUE THREAD

**Issue by EricaGrimaldi** [UniprJRC/DSconMATLAB#400]
A pagina 54 del testo, riga 5, "devano" deve essere sostituito con "devono".

**Comment by MarcoRianiUNIPR** [comment]
Mi raccomando di controllare prima la pagina di errata corrige
![image](https://github.com/user-attachments/assets/a7213fde-0a6a-4c03-951a-1ed11bacb709)
