### ISSUE TITLE
Errore di ortografia nel file "TimeTableImp.pdf"

### ISSUE THREAD

**Issue by Benedetto0301** [UniprJRC/DSconMATLAB#401]
![WhatsApp Image 2024-10-04 at 11 47 32](https://github.com/user-attachments/assets/32033c3d-3be3-4dae-b645-cee285d3eb89)

Dovrebbe essere scritto "mostrare" al posto di "mostare"

**Comment by MarcoRianiUNIPR** [comment]
Segnalazione corretta. Stasera il file viene aggiornato nel sito di Giappichelli. Lascio aperto l'issue

**Comment by MarcoRianiUNIPR** [comment]
Corretto nel sito Giappichelli
