### ISSUE TITLE
Errore di battitura che non ostacola la comprensione

### ISSUE THREAD

**Issue by EricaGrimaldi** [UniprJRC/DSconMATLAB#402]
A pagina 64 del testo, paragrafo 1.8.5, dopo la sintassi del comando plot, "x e v sono.." deve essere modificato con "x e y sono.."

**Comment by MarcoRianiUNIPR** [comment]
Mi raccomando prima di scrivere di controllare la pagina di errata corrige del testo.
Questo refuso è stato già segnalato l'anno scorso
![image](https://github.com/user-attachments/assets/36f57b61-938e-47c0-b33a-1ed203dd8837)
