### ISSUE TITLE
Errore di battitura in AnalisiEsplorativeDatiOUT

### ISSUE THREAD

**Issue by leonardospinetti** [UniprJRC/DSconMATLAB#404]
A pagina 5, viene usato "citiesItalyWithZome" anziché "citiesItalyWithZone".
<img width="1128" alt="Screenshot 2024-10-06 at 11 38 28 AM" src="https://github.com/user-attachments/assets/1477ce18-a172-4f67-95ed-231474c15265">

**Comment by MarcoRianiUNIPR** [comment]
Osservazione corretta. Attendo la segnalazioni di eventuali altri refusi. Lascio aperto l'issue

**Comment by MarcoRianiUNIPR** [comment]
File corretto nel sito di Giappichelli
