### ISSUE TITLE
errore di battitura AnalisiEsplorativeDati slide 7

### ISSUE THREAD

**Issue by Alexf02** [UniprJRC/DSconMATLAB#405]
![IMG_9828 2](https://github.com/user-attachments/assets/c1334b4f-8514-4664-bdc7-3488e028c109)

**Comment by MarcoRianiUNIPR** [comment]
Osservazione assolutamente corretta. Bravo

**Comment by MarcoRianiUNIPR** [comment]
File corretto nel sito di Giappichelli
