### ISSUE TITLE
Mancanza precisazione conversione in string in AnalisiEsplorativeDatiOUT slide 9

### ISSUE THREAD

**Issue by IreneGalli** [UniprJRC/DSconMATLAB#406]
Nel comando array2table è necessario prima convertire il categorical con il nome delle classi in string, oppure direttamente nel codice della table.

**Comment by MarcoRianiUNIPR** [comment]
Osservazione assolutamente corretta

**Comment by MarcoRianiUNIPR** [comment]
File corretto nel sito di Giappichelli
