### ISSUE TITLE
errore di battitura

### ISSUE THREAD

**Issue by SILVIAZIZZI** [UniprJRC/DSconMATLAB#407]
a pag 57 del testo nella 7 riga del codice è stato scritto "statementn" al posto di "statement"

**Comment by MarcoRianiUNIPR** [comment]
Dato che sopra c'è scritto 
statement1
...
statement2
....
è chiaro che deve inserire statementn e non statement

![image](https://github.com/user-attachments/assets/40db1000-c17e-45b5-aac9-96225e3205db)

Si che di seguito si fa esplicito riferimento allo statementn

**Comment by SILVIAZIZZI** [comment]
Chiaro, grazie!
