### ISSUE TITLE
Errore di battitura file OperazioniMatriciOUT[1]

### ISSUE THREAD

**Issue by Alessia16022002** [UniprJRC/DSconMATLAB#408]
![Screenshot 2024-10-07 235757](https://github.com/user-attachments/assets/e16171e6-bae5-43de-8ee6-4b66ffe0bed1)

Per visualizzarle nella Command Windows:
disp('Ultime 10 righe della table dei profili colonna')

**Comment by MarcoRianiUNIPR** [comment]
Già segnalato la settimana scorsa e già corretta
v. issue #388
