### ISSUE TITLE
Errore di battitura capitolo 5 pag 166

### ISSUE THREAD

**Issue by yousrachk** [UniprJRC/DSconMATLAB#409]
nel libro c'è scritto: In Matlab la funzione di ripartizione della distribuzione normale 'si calcolata' invece di 'si calcola'

**Comment by MarcoRianiUNIPR** [comment]
Già segnalata l'anno scorso.

![image](https://github.com/user-attachments/assets/d7dc1057-70c6-41bd-84cf-02cd490a772e)

Mi raccomando di controllare la pagina di errata corrige prima di scrivere
