### ISSUE TITLE
Errore di battitura nel file TimeTableOut

### ISSUE THREAD

**Issue by yousrachk** [UniprJRC/DSconMATLAB#410]
![8F327067-1863-4319-BFD7-44DFF34EF6A0](https://github.com/user-attachments/assets/a59a833c-d859-4113-9c88-a868d29ef5d0)

nel primo commento dell’esercizio c’è scritto 
% Mostro tr per capire l’intervallo di tempo che va ad estrarre anziché che vado ad estrarre

**Comment by MarcoRianiUNIPR** [comment]
In questo caso "va ad estrarre" si riferisce alla variabile `tr`
