### ISSUE TITLE
Errore battitura nel file distribuzioni.pdf

### ISSUE THREAD

**Issue by GaetanoMoretti** [UniprJRC/DSconMATLAB#411]
![Screenshot 2024-10-08 105156](https://github.com/user-attachments/assets/a76fe752-efd7-4161-9cbf-d001077cd095)

Errore di battitura nella prima pagina del file,
"oggetp", nella prima riga della seconda attività
(dopo "FILE DI RIEPILOGO AL CAPITOLO 5", 3 riga)

**Comment by MarcoRianiUNIPR** [comment]
Osservazione corretta.

**Comment by MarcoRianiUNIPR** [comment]
File corretto nel sito di Giappichelli
