### ISSUE TITLE
Errori di battitura in distribuzioni.pdf

### ISSUE THREAD

**Issue by leonardospinetti** [UniprJRC/DSconMATLAB#414]
Pagina 1, anziché "oggetto" è stato scritto. "oggettp" e sotto anziché "libertà" è stato scritto "libertò".
<img width="959" alt="Screenshot 2024-10-08 at 11 20 42 AM" src="https://github.com/user-attachments/assets/ae6a247d-f6e1-401c-8c1a-5d35a678bb5d">

**Comment by MarcoRianiUNIPR** [comment]
Osservazione corretta

**Comment by MarcoRianiUNIPR** [comment]
File corretto nel sito di Giappichelli
