### ISSUE TITLE
Errore di battitura in TimeTableImpOut

### ISSUE THREAD

**Issue by leonardospinetti** [UniprJRC/DSconMATLAB#415]
Pagina 6, viene scritto "creare mostrare il grafico" senza una "e" o altro.
<img width="811" alt="Screenshot 2024-10-08 at 11 57 44 AM" src="https://github.com/user-attachments/assets/dd27d114-7f30-482b-b397-748ae664ebd4">

**Comment by MarcoRianiUNIPR** [comment]
Osservazione corretta

**Comment by MarcoRianiUNIPR** [comment]
File corretto nel sito di Giappichelli
