### ISSUE TITLE
errore di battitura su 3AnalisiEsplorativeDatiOUT

### ISSUE THREAD

**Issue by ArdjanCelislami** [UniprJRC/DSconMATLAB#416]
Salve Prof,
ho notato alcuni errori di battitura nel file e sono i seguenti:
(pag 2)
<img width="794" alt="Screenshot 2024-10-08 alle 12 59 44" src="https://github.com/user-attachments/assets/959e1d4b-b2bc-4e07-9630-6e9517a4a4b0">

(pag 5)
<img width="814" alt="Screenshot 2024-10-08 alle 13 03 29" src="https://github.com/user-attachments/assets/b9e15b9c-322c-4aa4-ada8-d7666a5aa5ea">

(pag 5)
<img width="814" alt="Screenshot 2024-10-08 alle 12 57 43" src="https://github.com/user-attachments/assets/0c86980f-8d00-4ddc-91ae-ab8a91e6d924">

**Comment by MarcoRianiUNIPR** [comment]
File corretto nel sito di Giappichelli
