### ISSUE TITLE
Errore di battitura

### ISSUE THREAD

**Issue by sofiadallatana** [UniprJRC/DSconMATLAB#421]
https://github.com/UniprJRC/DSconMATLAB/blob/b40d29a02a70ad243758923d5b84f2cab67807c3/matlabfiles/capUnivariate/summaryIniziale.m#L4

righe 43-46
Xt1=groupcounts(Xt,"Education");
% consente di avere in output una table con i livello**d i** Education
% Se l'input è un vettore matrice o cell array allora 
[freq,modalita,freqperc]=groupcounts(Xt.Education);

CORRETTO
Xt1=groupcounts(Xt,"Education");
% consente di avere in output una table con i livello di Education
% Se l'input è un vettore matrice o cell array allora 
[freq,modalita,freqperc]=groupcounts(Xt.Education);

**Comment by sofiadallatana** [comment]
promemoria mail inviata a sofia.dallatana@studenti.unipr.it in data 01/10
tabella con valori x10 segnalata all'esercitazione

**Comment by MarcoRianiUNIPR** [comment]
Correzione effettuata nel file e "pushata" su GitHub. Grazie per la segnalazione
