### ISSUE TITLE
errori di battitura che non ostacolano la comprensione nel file "distribuzioni"

### ISSUE THREAD

**Issue by IreneGalli** [UniprJRC/DSconMATLAB#425]
Nella slide 3 del citato file è presente l'errore "comprei" invece che "compresi" nel primo pallino delle deduzioni e "compreo" invece che "compres" nell'istruzione di calcolo.

**Comment by MarcoRianiUNIPR** [comment]
Segnalazione corretta.
Attendo a fare le correzioni nel sito di Giappichelli qualora vengano trovati altri refusi

**Comment by MarcoRianiUNIPR** [comment]
Corretto nel sito di Giappichelli
