### ISSUE TITLE
Errore di battitura nelle slides, lezione 7 ottobre 2 parte

### ISSUE THREAD

**Issue by GaetanoMoretti** [UniprJRC/DSconMATLAB#426]
![Screenshot 2024-10-09 193428](https://github.com/user-attachments/assets/fbf7dcb3-bfed-46a8-80cb-918bee96eaa8)

Errore di battitura nelle slides, lezione 7 ottobre 2 parte.
Nel titolo della slide 237, è scritto tra parentesi "rischio di shorfall", invece che "shortfall".

**Comment by MarcoRianiUNIPR** [comment]
Osservazione corretta. Grazie per la segnalazione
