### ISSUE TITLE
Errore di battitura nel file "TimeTableImpOUT"

### ISSUE THREAD

**Issue by Saverio2604** [UniprJRC/DSconMATLAB#428]
![Screenshot 2024-10-10 113810](https://github.com/user-attachments/assets/391b6f25-d789-4115-8f6e-fb19c4f65f64)
 
"correspondenti": Deve essere corretto in "corrispondenti"

**Comment by MarcoRianiUNIPR** [comment]
Corretto. Lascio aperto l'issue fino a quando non ci sarà la nuova versione del file nel sito di Giappichelli

**Comment by MarcoRianiUNIPR** [comment]
Corretto file nel sito di Giappichelli. Per favore mi dica se ora è tutto a posto.
