### ISSUE TITLE
Errore battitura che non ostacola la comprensione sul file "3AnalisiEsplorativeDatiOUT[1]"

### ISSUE THREAD

**Issue by Alessia16022002** [UniprJRC/DSconMATLAB#439]
![Screenshot 2024-10-11 112952](https://github.com/user-attachments/assets/450c31b6-27ee-44a7-b010-43f0e20404f4)

%Chiamata a grpstatsFS con la variabile di raggruppamento

**Comment by MarcoRianiUNIPR** [comment]
Osservazione corretta
Non si finisce mai di correggere i refusi
Lascio l'issue aperto fino a quando non ci sarà la nuova versione del file nel sito di Giappichelli

**Comment by MarcoRianiUNIPR** [comment]
File aggiornato nel sito di Giappichelli
