### ISSUE TITLE
Errore di battitura che ostacola la comprensione 

### ISSUE THREAD

**Issue by ILIJA-PETKOV** [UniprJRC/DSconMATLAB#440]
**Errore di battitura alla pagina 190 nella formula di distribuzione normale bivariata con variabili correlate.**
[IMG_0135.pdf](https://github.com/user-attachments/files/17341838/IMG_0135.pdf)
Nella prima parte della formula nella prima frazione al denominatore  dovrebbe essere corretta con 2* pi * sigma di x * sigma di y * sqrt(1-rho^2)

**Comment by MarcoRianiUNIPR** [comment]
Mi raccomando di consultare la pagina di errata corrige prima di scrivere.

![image](https://github.com/user-attachments/assets/d29dfdf3-c551-4892-8e84-f6314723eb79)
