### ISSUE TITLE
Errore mancato inserimento del codice nel file TimeTableImpOUT

### ISSUE THREAD

**Issue by fatimaazedine** [UniprJRC/DSconMATLAB#441]
<img width="569" alt="image" src="https://github.com/user-attachments/assets/0a3c3432-7608-4edd-a92f-05fae2f9db55">

Alla fine della seconda pagina del file l'esercizio chiede di calcolare alcuni indici. Nella pagina successiva manca il codice per poter creare la tabella che è riportata. Ho provato a creare il codice. Per poter calcolare tutti gli indici richiesti si dovrebbe utilizzare il codice OUT=grpstatsFS(Xt) che non funziona perché la table "Xt" è una timetable. Per cui si deve prima trasformare la timetable in una table tramite l'istruzione "timetable2table" e solo dopo utilizzare la funzione grpstatsFS.

<img width="467" alt="image" src="https://github.com/user-attachments/assets/8fa7e5dc-aac4-49a4-922f-48a090583f0d">

**Comment by MarcoRianiUNIPR** [comment]
La versione di FSDA dello scorso meso aveva questo problema. Ora questo bug è stato "fixed".
Di conseguenza, mi raccomando sempre di controllare di avere l'ultima versione di FSDA.
Provi a disinstallare la versione che ha e ad installare la nuova versione e mi faccia sapere

p.s. per chi è coraggioso e vuole vedere il codice di grpstatsFS può digitare nella Command Window 

edit grpstatsFS 

e andare alla riga 326

![image](https://github.com/user-attachments/assets/fb07e972-21e1-44f8-8534-62fcd1c37b4f)

l'istruzione istimetable(TBL) è stata aggiunta

**Comment by fatimaazedine** [comment]
Prof, comunque nel file manca la riga di codice per creare la tabella che viene riportata sopra. Ci sono solo queste due righe di codice. 
<img width="542" alt="image" src="https://github.com/user-attachments/assets/3cfe88ea-86fe-4382-89ae-9dc1447300a7">

**Comment by MarcoRianiUNIPR** [comment]
Giusto molto brava!!! 
Effettivamente mancava la riga che menzionava.
Tra poco faccio l'upload del nuovo file

**Comment by MarcoRianiUNIPR** [comment]
Sito web di Giappichelli aggiornato
