### ISSUE TITLE
Domanda esercitazione AnalisiEsplorativeDatiOUT

### ISSUE THREAD

**Issue by MARIA-PISCINA** [UniprJRC/DSconMATLAB#443]
Nella seguente riga di codice per effettuare il controllo di uguaglianza, sarebbe corretto scrivere il seguente codice:
assert(isequal(tabSolo1,tabSolo1CHK), ‘gli output differiscono’);

![IMG_0742](https://github.com/user-attachments/assets/3cb8be8f-bcb7-47e8-925c-73f8df865a83)

**Comment by MarcoRianiUNIPR** [comment]
Sì sì questo è stato corretto nella versione che ho appena caricato

**Comment by MarcoRianiUNIPR** [comment]
Sito web di Giappichelli aggiornato
