### ISSUE TITLE
Errore di ortografia nel file "distribuzioniOUT"

### ISSUE THREAD

**Issue by Benedetto0301** [UniprJRC/DSconMATLAB#444]
![WhatsApp Image 2024-10-11 at 15 45 54](https://github.com/user-attachments/assets/b4d3c434-59a5-4bb0-885a-b1f562c43dcc)

A pagina 12 "ouptut" dovrebbe essere "output"

**Comment by MarcoRianiUNIPR** [comment]
Osservazione corretta. 
Issue aperto fino a quando non ci sarà la correzione nel sito di Giappichelli

**Comment by MarcoRianiUNIPR** [comment]
Sito web di Giappichelli aggiornato
