### ISSUE TITLE
Errore di ortografia nel file "preliminari.pdf"

### ISSUE THREAD

**Issue by Benedetto0301** [UniprJRC/DSconMATLAB#445]
![WhatsApp Image 2024-10-11 at 15 49 19](https://github.com/user-attachments/assets/4fbec131-0b05-4c9d-a2b2-75ed987fa15a)

A pagina 2 la parola "fuzione" dovrebbe essere "funzione"

**Comment by MarcoRianiUNIPR** [comment]
Osservazione corretta

Issue aperto fino a quando non ci sarà la correzione nel sito di Giappichelli

**Comment by MarcoRianiUNIPR** [comment]
Sito web di Giappichelli aggiornato
