### ISSUE TITLE
Errore di ortografia nel file "preliminari"

### ISSUE THREAD

**Issue by Saverio2604** [UniprJRC/DSconMATLAB#446]
![Screenshot 2024-10-11 155043](https://github.com/user-attachments/assets/aa65a289-dd37-4bad-8f90-91a4b4d4cd5c)

"caldendarduration": Deve essere corretto in "calendarduration" (presente nella frase "Per la differenza tra duration e caldendarduration")

pag.2

**Comment by MarcoRianiUNIPR** [comment]
Osservazione corretta

Issue aperto fino a quando non ci sarà la correzione nel sito di Giappichelli

**Comment by MarcoRianiUNIPR** [comment]
Corretto nel sito di Giappichelli
