### ISSUE TITLE
Errore di ortografia nel file "distribuzioniOUT.pdf" 

### ISSUE THREAD

**Issue by Benedetto0301** [UniprJRC/DSconMATLAB#447]
![WhatsApp Image 2024-10-11 at 15 46 39](https://github.com/user-attachments/assets/890f8a1f-ded6-42e7-b400-620de8dfbcd4)

A pagina 8 la parola "disuaglianza" dovrebbe essere "disuguaglianza"

**Comment by MarcoRianiUNIPR** [comment]
Sito web di Giappichelli aggiornato
