### ISSUE TITLE
Errore di ortografia nel file "preliminari.pdf"

### ISSUE THREAD

**Issue by Benedetto0301** [UniprJRC/DSconMATLAB#448]
![WhatsApp Image 2024-10-11 at 15 53 25](https://github.com/user-attachments/assets/0da81603-ab79-4d57-876c-66540f01cc62)

A pagina 3 la parola "artimetiche" dovrebbe essere "aritmetiche"

**Comment by MarcoRianiUNIPR** [comment]
Osservazione corretta
Issue aperto fino a quando non ci sarà la correzione nel sito di Giappichelli

**Comment by MarcoRianiUNIPR** [comment]
Sito web di Giappichelli aggiornato
