### ISSUE TITLE
ERRORE DI BATTITURA CHE NON OSTACOLA LA COMPRENSIONE

### ISSUE THREAD

**Issue by ANGELABORRELLO** [UniprJRC/DSconMATLAB#449]
Pag. 108, punto 5) dell'esercizio 3.4 del libro : alla quinta riga, sostituire '...deve contenere (-2 0]. mostrare...' con '...deve contenere (-2 0]. Mostrare...' .  Quindi aggiungere semplicemente la 'M' maiuscola

**Comment by MarcoRianiUNIPR** [comment]
Mi raccomando di consultare la pagina di errata corrige prima di scrivere

![image](https://github.com/user-attachments/assets/059cabb9-fb77-4c74-831a-c6dbb838971d)
