### ISSUE TITLE
ERRORE CHE NON OSTACOLA LA COMPRENSIONE 

### ISSUE THREAD

**Issue by ANGELABORRELLO** [UniprJRC/DSconMATLAB#450]
Pagina 109 del libro, sesta riga:  '... h.histogram(...) ...' ha la seconda parentesi e i punti di sospensione di colore verde (colore che viene usato nei 'commenti' di matlab), mentre la restante parte è di colore nero.
[pag109.pdf](https://github.com/user-attachments/files/17343648/pag109.pdf)

**Comment by MarcoRianiUNIPR** [comment]
Osservazione corretta
Aggiunto in errata corrige nella sezione 

**COLORAZIONE DEL CODICE ERRATA**

![image](https://github.com/user-attachments/assets/65a11f90-4dcd-40ce-bcc1-a0c9560bbc23)
