### ISSUE TITLE
ERRORE DI BATTITURA

### ISSUE THREAD

**Issue by ANGELABORRELLO** [UniprJRC/DSconMATLAB#451]
Pag.61, riga 4 (escludendo la parti di codice): 'Se cond è vera non viene prodotto alcun output, al contrario se cond è false...' sostituire 'false' con 'falsa'.

**Comment by MarcoRianiUNIPR** [comment]
Già segnalato. Mi raccomando di fare il pull per avere sempre la versione aggiornata del file

![image](https://github.com/user-attachments/assets/6686f8ab-3de6-4fd8-a10d-bd810cfe92d7)
