### ISSUE TITLE
Errore di battitura nel file BaseOUT

### ISSUE THREAD

**Issue by MicheleStella** [UniprJRC/DSconMATLAB#452]
A pagina 12 del file BaseOUT, nel commento si deve sostituire z con Z, dato che fa riferimento alla Matrice appena creata denominata Z.

![Immagine WhatsApp 2024-10-11 ore 16 35 42_317bfe68](https://github.com/user-attachments/assets/40483e4c-50e6-45f1-a616-f1d12b1f033d)

**Comment by MarcoRianiUNIPR** [comment]
Osservazione corretta


Issue aperto fino a quando non ci sarà la correzione nel sito di Giappichelli

**Comment by MarcoRianiUNIPR** [comment]
Sito web di Giappichelli aggiornato
