### ISSUE TITLE
Errore di battitura in distribuzioni OUT

### ISSUE THREAD

**Issue by KM-Kev** [UniprJRC/DSconMATLAB#453]
Pagina 8 del file nel commento dei valori all'interno della table
dopo 55,56%, c'è scritto nel caso della distribuzioni.

dovrebbe essere "nel caso della distribuzione".

**Comment by MarcoRianiUNIPR** [comment]
Osservazione corretta

Issue aperto fino a quando non ci sarà la correzione nel sito di Giappichelli

**Comment by MarcoRianiUNIPR** [comment]
Sito web di Giappichelli aggiornato
