### ISSUE TITLE
problema nel importare dati da una pagina web

### ISSUE THREAD

**Issue by CrisG99** [UniprJRC/DSconMATLAB#455]
![Screenshot (90)](https://github.com/user-attachments/assets/2910328c-95ce-4bf9-97d6-766f9a7b9211)

Buona sera, ho iniziato il primo esercizio di riepilogo 4.1 pg 160, ma al momento del Run mi appare questo. Cosa devo fare?

**Comment by MarcoRianiUNIPR** [comment]
Il messaggio di errore le fa capire che ha sbagliato a scrivere l'indirizzo web.

In altri termini, l'indirizzo del sito web  (come scritto correttamente nel testo dell'esercizio e come riportato nella slide iniziale del corso) 
è 
![image](https://github.com/user-attachments/assets/c6994dd6-4dc7-450d-accf-af10eefc4fdf)

Di conseguenza l'indirizzo corretto è 

%% Caricamento dati
X=webread('http://www.riani.it/start.xlsx');

e non come ha scritto lei
X=webread('https://www.riani.it/start.xlsx');

http e https sono due protocolli diversi. 
Se vuole utilizzare il protocollo https deve scrivere

X=webread('https://riani.unipr.it/start.xlsx')

La ringrazio per il suo messaggio. Il fatto di non scrivere un comando in maniera corretta e pretendere di non avere un errore è una cosa che vedo fare in maniera regolare. 

Mi faccia sapere se ha capito e/o se sono stato chiaro.

**Comment by CrisG99** [comment]
Tutto chiaro! grazie mille prof.

**Comment by MarcoRianiUNIPR** [comment]
Lascio aperto l'issue per qualche giorno poiché potrebbe essere utile per altre persone.
