### ISSUE TITLE
Incomprensione in esercizio del libro

### ISSUE THREAD

**Issue by GaetanoMoretti** [UniprJRC/DSconMATLAB#459]
Buonasera professore, ho riscontrato un problema nello svolgimento dell'esercizio 3.9, pagina 125 del libro, precisamente nel punto 5 (l'ultima riga della pagina e le prime righe della pagina dopo).
Nella traccia viene richiesto di posizionare due variabili ("Gender" e "Seniority") sulle righe e di includere nella tabella la mediana della variabile "Wage".
Nel codice di soluzione viene inserita per le colonne la variabile "Education", nonostante non vi sia richiesta esplicita nella consegna.

Questa la consegna:
![Immagine WhatsApp 2024-10-13 ore 17 05 15_19eb0154](https://github.com/user-attachments/assets/a7a6bef0-3128-4e93-9ccb-e511015ffbf9)
![Immagine WhatsApp 2024-10-13 ore 17 06 42_6197ada6](https://github.com/user-attachments/assets/4b1c3724-a28a-4aeb-93b4-9f6900e712e6)

Questa la soluzione (del punto in questione):
![Immagine WhatsApp 2024-10-13 ore 17 06 08_e5f63a73](https://github.com/user-attachments/assets/5085383f-7494-4976-befa-a3e00065c2ba)

Io avevo svolto l'esercizio senza includere la variabile "Education" sulle colonne, in questo modo
![Screenshot 2024-10-13 171326](https://github.com/user-attachments/assets/a89381f8-3e67-4ef4-83ba-d73cf8d7931b)

**Comment by MarcoRianiUNIPR** [comment]
Mi raccomando sempre di consultare la pagina di errata corrige prima di scrivere.

![image](https://github.com/user-attachments/assets/a1671f1c-cd56-4549-8ff7-baf51efea655)


Comunque, la sua segnalazione è assolutamente corretta. Nel testo non era scritto che la variabile Education doveva essere inserita nelle colonne.

**Comment by GaetanoMoretti** [comment]
Certamente, errore mio.
Grazie mille

**Comment by MarcoRianiUNIPR** [comment]
Nessun errore. Nella mia vita ho studiato tanti libri e ho trovato "molto frustante" non capire una determinata cosa poiché c'era un refuso nel libro. Ovviamente i refusi non possono essere eliminati. La pagina di errata corrige e l'interazione tramite gli issues e/o nelle sessioni pratiche al laboratorio serve per fare in modo che l'apprendimento sia il più possibile facilitato. E' sempre meglio scrivere, chiedere e confrontarsi una volta in più che una in meno. La ringrazio per la segnalazione
