### ISSUE TITLE
errore di battitura che non ostacola la comprensione

### ISSUE THREAD

**Issue by nicolabochhi** [UniprJRC/DSconMATLAB#468]
a pagina 284 del libro di testo sulla riga 18 del codice invece di scrivere set c'è scritto get

**Comment by MarcoRianiUNIPR** [comment]
Confermo che get consente di recuperare (ossia visualizzare, ossia leggere) una proprietà di un oggetto (in questo caso un handle grafico)
![image](https://github.com/user-attachments/assets/959f727b-3545-4f39-80b0-344cf45bb909)

Al contrario l'istruzione set consente di settare (ossia modificare) una proprietà di un oggetto.

Di conseguenza: il commento si riferisce a `get `ma il codice fa riferimento a `set`

Mi faccia sapere se sono stato chiaro
