### ISSUE TITLE
errore di battitura 

### ISSUE THREAD

**Issue by nicolabochhi** [UniprJRC/DSconMATLAB#469]
a pagina 190 del libro nell'esercizio 5.9 nella riga 6 del codice bisogna scrivere mesh(x,y,z)  invece che solo mesh(z)

**Comment by MarcoRianiUNIPR** [comment]
Mi raccomando di consultare la pagina di errata corrige prima di scrivere

![image](https://github.com/user-attachments/assets/99bf0f8b-f923-4c56-b49b-db128166f86f)
