### ISSUE TITLE
Errore di battitura nel file MatriceDiagrammiDispersione

### ISSUE THREAD

**Issue by KM-Kev** [UniprJRC/DSconMATLAB#470]
a riga 70 c'è scritto se la scatterplot Matrix 

dovrebbe essere se lo scatterplot Matrix

**Comment by MarcoRianiUNIPR** [comment]
per scatterplot matrix intendo la matrice dei diagrammi di dispersione di conseguenza secondo me può rimanere la dizione con l'articolo "la"
