### ISSUE TITLE
HW 4.5 SITO GIAPPICHELLI

### ISSUE THREAD

**Issue by ANGELABORRELLO** [UniprJRC/DSconMATLAB#472]
Nella linea di codice 25, i 'caratteri 7-8' non dovrebbero indicare il 'giorno' invece dell'ora? 
'... % i primi 4 caratteri si riferiscono all'anno
     %caratteri 5-6 mese
     %caratteri 7-8 ora
....'
non dovrebbe essere
'... % i primi 4 caratteri si riferiscono all'anno
     %caratteri 5-6 mese
     %caratteri 7-8 giorno
....' ?

**Comment by MarcoRianiUNIPR** [comment]
Assolutamente corretto.
Brava
Lascio aperto l'issue fino a quando non sarà corretto nel sito di Giappichelli

**Comment by MarcoRianiUNIPR** [comment]
File corretto e aggiornato nel sito di Giappichelli
