### ISSUE TITLE
ERRORE DI BATTITURA HW 4.5

### ISSUE THREAD

**Issue by ANGELABORRELLO** [UniprJRC/DSconMATLAB#473]
HW 4.5 del sito Giappichelli: nella riga 6 del codice (che è il commento) c'è scritto ' %datastr = ...' , mentre nelle righe di codice successive (riga 7 e riga 9) c'è scritto 'datstr' , quindi senza la 'a' .

**Comment by MarcoRianiUNIPR** [comment]
Corretto

Lascio aperto l'issue fino a quando non sarà corretto nel sito di Giappichelli

**Comment by MarcoRianiUNIPR** [comment]
Corretto nel sito di Giappichelli
