### ISSUE TITLE
Errore di battitura nel file AnalisiEsplorativeDati

### ISSUE THREAD

**Issue by giorgiapignoli** [UniprJRC/DSconMATLAB#477]
Quando viene richiesto di creare la tabella citiesT, è poi successivamente richiesto di assegnare alle righe 3:10 il valore 1e06. Questo è però richiesto sulla table citiesItaly, ma la differenza tra i risultati degli indici non robusti si può verificare trasformando i valori di citiesT, la tabella su cui si stava lavorando

**Comment by MarcoRianiUNIPR** [comment]
Questo è già stato segnalato e corretto circa 10 giorni fa.
Per favore controlli di avere il file con data segue
![image](https://github.com/user-attachments/assets/d4510268-4379-48a2-9035-b1f206acf0ad)

e mi faccia sapere
