### ISSUE TITLE
Errore pagina 38, es 1.2

### ISSUE THREAD

**Issue by Dallo2001** [UniprJRC/DSconMATLAB#48]
**Sostituire**: Creare una matrice 2x3 chiamata mn compost**o** dai primi sei numeri
naturali

**Con**: Creare una matrice 2x3 chiamata mn compost**a** dai primi sei numeri
naturali

Credo sia errato il "composto" in quanto si riferisce alla matrice che è femminile.

**Comment by UniprJRC** [comment]
Inserita in errata corrige, grazie

p. 38 riga 2 (segnalato da Dallo 2001 19/09/2023)
Rimpiazzare
Creare una matrice 2x3 chiamata mn composto dai primi sei numeri naturali
con
Creare una matrice 2x3 chiamata mn composta dai primi sei numeri naturali
