### ISSUE TITLE
Errore di battitura nel file AnalisiEsplorativeDatiOUT

### ISSUE THREAD

**Issue by MicheleStella** [UniprJRC/DSconMATLAB#480]
A pagina 3 del file, "% Controllo l'uguaglianza tra **statTable** e **statTableCHK**" con  "% Controllo l'uguaglianza tra **tabSolo1** e **tabSolo1CHK**".

![Immagine WhatsApp 2024-10-15 ore 18 29 41_e90b1771](https://github.com/user-attachments/assets/2b0c9487-af66-4f72-86db-6e1b5233c73b)

**Comment by MarcoRianiUNIPR** [comment]
Già corretto la settimana scorsa

Mi raccomando di controllare di avere l'ultima versione del file

![image](https://github.com/user-attachments/assets/4dbc0a4f-158f-457d-8d14-c3028f4b5697)
