### ISSUE TITLE
Ripetizione pagina 37 del libro Data Science con MATLAB

### ISSUE THREAD

**Issue by CristinaElenaConstantinescu** [UniprJRC/DSconMATLAB#482]
Pagina 37 del libro di testo. 
Paragrafo 1.4.1 Creazione dei diversi tipi di array
[...]
"Ad esempio, per creare un array numerico, ad esempio un vettore riga (orizzontale) ... "

Vi è una ripetizione : "ad esempio" si ripete due volte. Sarebbe più corretto dire : " Per creare un array numerico, ad esempio un vettore riga (orizzontale ) ...".

**Comment by MarcoRianiUNIPR** [comment]
La ringrazio per la segnalazione ed ha perfettamente ragione sulla ripetizione.
Ho annotato questa correzione nei miei appunti, ma non la inserisco in errata corrige.

Ci tengo a precisare, però, che la sua segnalazione è assolutamente corretta e verrò incorporata nella prossima edizione.
