### ISSUE TITLE
ERRORE BATTITURA CHE NON OSTACOLA LA COMPRENSIONE

### ISSUE THREAD

**Issue by ANGELABORRELLO** [UniprJRC/DSconMATLAB#484]
Pag 133, HW 3.5, riga 2:  '... Questo dataset contiene il numero di visite al supermercato (visits) l'età (age), il numero ... ' . 
Credo manchi una virgola tra '(visits)' e 'l'età', dovrebbe essere: '... Questo dataset contiene il numero di visite al supermercato (visits), l'età (age), il numero ... '

**Comment by MarcoRianiUNIPR** [comment]
Fatto grazie

![image](https://github.com/user-attachments/assets/849476e4-4c75-4b6e-961c-7da3d8b0cbf3)
