### ISSUE TITLE
Errore di battitura in preliminariOut

### ISSUE THREAD

**Issue by leonardospinetti** [UniprJRC/DSconMATLAB#488]
A pagina 6, è stato scritto "valòre" anzichè "valore".
<img width="1135" alt="Screenshot 2024-10-17 at 3 13 59 PM" src="https://github.com/user-attachments/assets/18983e0e-a83c-464b-90ac-c9876cc88b70">

**Comment by MarcoRianiUNIPR** [comment]
Corretto grazie. Lascio l'issue aperto fino a quando non viene corretto nel sito di Giappichelli

**Comment by MarcoRianiUNIPR** [comment]
File corretto nel sito Giappichelli
