### ISSUE TITLE
ERRORE COLORAZIONE

### ISSUE THREAD

**Issue by ANGELABORRELLO** [UniprJRC/DSconMATLAB#494]
Pag.198, prima riga del codice output, errore nella colorazione 'Matrice 4x4 di numeri casuali interi dall'insieme (1, 2, ..., 8)' : i tre puntini di sospensione, la virgola, l'8 e la parentesi ( **..., 8)** ) sono di colore verde.

**Comment by MarcoRianiUNIPR** [comment]
Fatto grazie
![image](https://github.com/user-attachments/assets/225edc80-d8d6-4219-bbc4-bb82d9dca978)
