### ISSUE TITLE
Errore di battitura nel libro DS con MATLAB

### ISSUE THREAD

**Issue by Marcob724** [UniprJRC/DSconMATLAB#496]
Pagina 148 riga 9: invece di "table" ci vorrebbe "timetable"

**Comment by MarcoRianiUNIPR** [comment]
Mi raccomando di consultare prima la pagina di errata corrige per capire se la segnalazione era già stata effettuata

![image](https://github.com/user-attachments/assets/91f79d10-e17c-4718-8d0d-b8e6edf688f1)
