### ISSUE TITLE
errore di battitura che non ostacola la comprensione

### ISSUE THREAD

**Issue by IreneGalli** [UniprJRC/DSconMATLAB#499]
Nelle soluzioni degli esercizi di riepilogo del capitolo 6 nel commento dell'es. HW6.3 è stato scritto erroneamente "listwise"
![Screenshot_18-10-2024_202010_biblioteca giappichelli it](https://github.com/user-attachments/assets/d4213951-ff64-4772-9e56-61551317d318)

**Comment by MarcoRianiUNIPR** [comment]
Corretto nel sito di Giappichelli

Grazie per la segnalazione

![image](https://github.com/user-attachments/assets/1cd62a6e-f877-4a5e-bfed-891953cf6459)
