### ISSUE TITLE
Errore di battitura pg 46, 1.5.3 Introduzione ai task

### ISSUE THREAD

**Issue by Dallo2001** [UniprJRC/DSconMATLAB#50]
Nella seconda riga del paragrafo 1.5.3 è presente un errore.
**Sostituire**: file .mlx
**Con**: file.mlx

Va eliminato lo spazio, in quanto su MATLAB non possono esserci presenti spazi nel nome del file.

**Comment by UniprJRC** [comment]
Questo non è un errore. Quando si parla di .mlx universalmente si intende file con estensione di tipo mlx.

Ad esempio file .docx sono i file di word con estensione docx.  

Di conseguenza la frase ...dentro il file .mlx... significa dentro il file che presenta estensione mlx.
