### ISSUE TITLE
Errore che non ostacola la comprensione 

### ISSUE THREAD

**Issue by ILIJA-PETKOV** [UniprJRC/DSconMATLAB#502]
A pagina 235 nell'esercizio 7.5 riga 4, dove c'è scritto utilizzare i quantili che seguono al posto di mettere il punto ( . ), non sarebbe più corretto utilizzare il doppio punto ( : ) ?

**Comment by MarcoRianiUNIPR** [comment]
Osservazione assolutamente corretta

Fatto grazie

![image](https://github.com/user-attachments/assets/57ab7580-6c6c-44fc-81a9-a08482289e75)
