### ISSUE TITLE
Errore che non ostacola la comprensione

### ISSUE THREAD

**Issue by GaetanoMoretti** [UniprJRC/DSconMATLAB#503]
Esercizio di riepilogo HW 4.1 a pagina 160 del libro.
Viene importata una tabella dal suo sito online, questa tabella riporta "ABRUZZI" invece che "ABRUZZO".
Si nota nell'immagine dalla prima label sull'asse x
Nella tabella ogni individuo che presenta la variabile regione di questo tipo presenta l'errore di battitura
![Screenshot 2024-10-19 143139](https://github.com/user-attachments/assets/2e70dc2a-c995-47c9-9726-2eb639b526f7)
![image](https://github.com/user-attachments/assets/a6974d9e-e4ba-4f2c-b709-445fadead2a8)

**Comment by MarcoRianiUNIPR** [comment]
v. issues #119 e #213

**Comment by MarcoRianiUNIPR** [comment]
Per capire se una segnalazione è stata già fatto basta cercare la parola chiave

Ad esempio la ricerca di abruzzi fornisce

![image](https://github.com/user-attachments/assets/0672cfd2-7e45-4512-a6b8-58f33983e8bd)
