### ISSUE TITLE
Errore che non ostacola la comprensione

### ISSUE THREAD

**Issue by emmaconta** [UniprJRC/DSconMATLAB#505]
A pag.202 nel testo dell'esercizio di riepilogo 5.8, c'è una ripetizione nella penultima frase: "utilizzando la funzione makedist" e "tramite la funzione makedist"

**Comment by MarcoRianiUNIPR** [comment]
Fatto grazie
![image](https://github.com/user-attachments/assets/c2f8927d-0fef-40a5-a55d-9a7c90fd59c2)
