### ISSUE TITLE
errore di battitura che non ostacola la comprensione

### ISSUE THREAD

**Issue by Anastasia2904** [UniprJRC/DSconMATLAB#511]
pag. 134 HW 3.10 "Costruire una tabella pivot in cui sulle righe ci siano gli iscritti **primi** e dopo il 2020."

**Comment by MarcoRianiUNIPR** [comment]
Come sempre mi raccomando di guardare l'errata corrige per capire se la segnalazione è già stata fatta

![image](https://github.com/user-attachments/assets/9557ea87-68c5-43ad-8052-53e2ed7dd6c6)
