### ISSUE TITLE
Correzione non presente 

### ISSUE THREAD

**Issue by ILIJA-PETKOV** [UniprJRC/DSconMATLAB#514]
A pagina 221 nell'esercizio HW 6.2 è richiesto di confrontare i p-value asintotici con quelli derivanti dall'implementazione Montecarlo utilizzando una soglia di tolleranza uguale a 0.0001. 
Sul sito di Giappichelli non è presente la soluzione.

**Comment by MarcoRianiUNIPR** [comment]
Ha assolutamente ragione.
La parte mancante dell'esercizio è stata aggiunta nel sito di Giappichelli
