### ISSUE TITLE
errore di battitura

### ISSUE THREAD

**Issue by gaiaalbani** [UniprJRC/DSconMATLAB#515]
pag 54 del libro, riga 5 riporta la parola "devano", parola corretta da inserire "devono".

**Comment by MarcoRianiUNIPR** [comment]
Ancora una volta:
mi raccomando di controllare la pagina di errata corrige prima di scrivere
![image](https://github.com/user-attachments/assets/9fc179d1-dda9-4670-899d-2463f9fb36af)
