### ISSUE TITLE
Errori di battitura che non ostacolano la comprensione nel file "CorrelazioneOUT"

### ISSUE THREAD

**Issue by MannaLuca** [UniprJRC/DSconMATLAB#516]
A pagina 2 c'è scritto "Illustrare come combiano" al posto di cambiano.
A pagina 4 nella frase "Generare un campione bivariato..." c'è scritto coeffiiciente al posto di coefficiente.
A pagina 5 nella frase "Stimare la varianza..." c'è scritto signicatività al posto di significatività 
Alla fine della pagina 6 c'è scritto indipentemente, al posto di indipendentemente.
A pagina 10 nella frase "Osservazione..." c'è scritto esericizio al posto di esercizio.
Alla fine della pagina 12 c'è scritto probabità al posto di probabilità. 
A pagina 13 nella frase "Dato che la probabilità..." c'è scritto leggeremente al posto di leggermente

**Comment by MarcoRianiUNIPR** [comment]
Bravo, grazie mille per queste segnalazioni. Tra breve le correggo nel sito di Giappichelli

**Comment by MarcoRianiUNIPR** [comment]
file aggiornato nel sito di Giappichelli
