### ISSUE TITLE
Errori di battitura

### ISSUE THREAD

**Issue by JulieMalmendier** [UniprJRC/DSconMATLAB#517]
pagina 60 -> la parola con 
![tempImageehgoHx](https://github.com/user-attachments/assets/4501942f-0ddd-4930-9f43-5e1271ab9900)

pagina 64 -> dopo "dove" è scritto x e v invece che x e y 

![tempImageD7oPiO](https://github.com/user-attachments/assets/a5f71e6c-95b6-40dd-8792-76235208d2f2)

**Comment by MarcoRianiUNIPR** [comment]
Ancora una volta (e sicuramente non sarà l'ultima volta) mi raccomando di consultare la pagina di errata corrige prima di scrivere
![image](https://github.com/user-attachments/assets/9321a7fe-99fc-430e-9b26-00bc1ef777f1)
