### ISSUE TITLE
errori di battitura su https://riani.unipr.it/MQF/

### ISSUE THREAD

**Issue by ArdjanCelislami** [UniprJRC/DSconMATLAB#519]
<img width="1440" alt="Screenshot 2024-10-25 alle 15 12 07" src="https://github.com/user-attachments/assets/2cda13ae-eb78-44ef-a62b-27c492c1ba17">

il primo errore è la battitura di una lettera sbagliata;
il secondo e il terzo sono il mancato spazio dopo il punto;
il quarto errore è una doppia spaziatura.

buona giornata!

**Comment by MarcoRianiUNIPR** [comment]
File corretto. La ringrazio per le segnalazioni
