### ISSUE TITLE
Errore pagina 83, esercizio 2.15

### ISSUE THREAD

**Issue by federico-baio** [UniprJRC/DSconMATLAB#52]
Nell'esercizio 2.15 di pagina 83 ,non è dichiarata la variabile 'n' che viene inserita nelle due matrici come numero di righe.

**Comment by UniprJRC** [comment]
Segnalazione corretta ed inserita in errata 
p. 83 nell'esercizio 2.15 la variabile n non è dichiarata (segnalato da federico-baio)
Aggiungere un numero intero a piacere per n. Ad esempio n=5; nella prima riga del codice
