### ISSUE TITLE
preappello  e materiale d'esame

### ISSUE THREAD

**Issue by CELINLT** [UniprJRC/DSconMATLAB#521]
buongiorno,
vorrei sapere se è previsto un preappello il  19 novembre ed eventualmente come poter iscrivermi.
Il materiale d'esame è dal capitolo 1 fino al capitolo 10 del libro ?

**Comment by MarcoRianiUNIPR** [comment]
Confermo che per l'esame di Statistica per la Digital Economy ci sarà un preappello. Dato che il 19 di novembre mi si è sovrapposto un altro impegno il preappello si terrà VEN 16 novembre. Su Elly inserisco tutte le informazioni tra breve.
Mi raccomando di utilizzare questo forum solo per gli argomenti dei corsi e non per le date degli appelli

**Comment by CELINLT** [comment]
buonasera,
la ringrazio per la rapida risposta, il materiale d'esame sarà fino al capitolo 9 o include anche il capitolo 10?

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________
