### ISSUE TITLE
errore di battitura

### ISSUE THREAD

**Issue by SILVIAZIZZI** [UniprJRC/DSconMATLAB#522]
pag 29 4° rigo l'organizzazione*,
pag 42 terzultima riga un'* etichetta

**Comment by MarcoRianiUNIPR** [comment]
Fatto grazie
![image](https://github.com/user-attachments/assets/87f08a4c-da8e-4346-a0c7-b70393d9a41e)

Il secondo refuso era già stato segnalato lo scorso anno (come sempre mi raccomando di consultare prima la pagina di errata corrige)

![image](https://github.com/user-attachments/assets/b52e9aa1-0941-4df7-aa11-81126c8ddb46)
