### ISSUE TITLE
Errori di battitura che non ostacolano la comprensione

### ISSUE THREAD

**Issue by SILVIAZIZZI** [UniprJRC/DSconMATLAB#523]
pag 44 paragrafo 1.5.2 secondo rigo di un'elaborazione*
pag 63 quintultimo rigo primo paragrafo "se si già si conosce" , se già si conosce*
pag 63 quartultimo rigo primo paragrafo dopo aver scritto*
pag 63 terzultimo rigo dopo averla selezionatA*

ho controllato che gli errori non fossero già presenti nell'errata corrige

**Comment by MarcoRianiUNIPR** [comment]
Il primo non credo posso essere considerato un refuso.
Secondo me si può dire sia "un'elaborazione" sia "una elaborazione".

Seconda segnalazione fatta
![image](https://github.com/user-attachments/assets/6b4fad22-4ddf-48b7-a782-30b23a29354f)

La terza segnalazione non la capisco

Quarta fatta
![image](https://github.com/user-attachments/assets/e24dba05-2023-482b-bfb1-c69c0d75ccf4)
