### ISSUE TITLE
Errore ortografico nel file GraficiAvanzatiOUT.pdf

### ISSUE THREAD

**Issue by Benedetto0301** [UniprJRC/DSconMATLAB#525]
Pagina 2, la parola "Ossercazione" dovrebbe essere "Osservazione"
![Screenshot 2024-11-04 091504](https://github.com/user-attachments/assets/cfd79f1a-2cee-43ef-a12b-f4944de63a78)

**Comment by MarcoRianiUNIPR** [comment]
Corretto grazie.
Aspetto altre segnalazioni e poi aggiorno il file nel sito di Giappichelli

**Comment by MarcoRianiUNIPR** [comment]
File aggiornato nel sito di Giappichelli
