### ISSUE TITLE
Errore di battitura nel file Associazione.pdf 

### ISSUE THREAD

**Issue by Benedetto0301** [UniprJRC/DSconMATLAB#527]
Pagina 2, la parola "eterogeità" dovrebbe essere "eterogeneità"
![Screenshot 2024-09-03 124507](https://github.com/user-attachments/assets/53c3ce6a-8e63-4ef2-a6b7-8b16979ee06b)

**Comment by MarcoRianiUNIPR** [comment]
Corretto grazie.
Aspetto altre segnalazioni e poi aggiorno il file nel sito di Giappichelli

**Comment by MarcoRianiUNIPR** [comment]
File aggiornato nel sito di Giappichelli
