### ISSUE TITLE
Errore di battitura nel file Associazione.pdf 

### ISSUE THREAD

**Issue by Benedetto0301** [UniprJRC/DSconMATLAB#528]
Pagina 2, la parola "riposta" dovrebbe essere "risposta" 
![image](https://github.com/user-attachments/assets/292c7176-0916-46f2-b9f8-3b17b327ade3)

**Comment by MarcoRianiUNIPR** [comment]
Corretto grazie.
Aspetto altre segnalazioni e poi aggiorno il file nel sito di Giappichelli
