### ISSUE TITLE
Errore di battitura nel file "AssociazioneOUT.pdf

### ISSUE THREAD

**Issue by Benedetto0301** [UniprJRC/DSconMATLAB#531]
Pagina 2, la parola "indpendenza" dovrebbe essere "indipendenza"
![image](https://github.com/user-attachments/assets/d7d671f9-c830-424a-984a-97a1cbc9335b)

**Comment by MarcoRianiUNIPR** [comment]
Corretto grazie.
Issue rimane aperto fino a quando il file viene aggiornato nel sito di Giappichelli

**Comment by MarcoRianiUNIPR** [comment]
File corretto nel sito di Giappichelli
