### ISSUE TITLE
Errore di battitura pg 59

### ISSUE THREAD

**Issue by Dallo2001** [UniprJRC/DSconMATLAB#54]
Nella seconda riga della pagina 59, 
**Sostituire**: (simile al ciclo **do** while....)
**Con**: (simile al ciclo **di** while)

**Comment by UniprJRC** [comment]
Questo non è un errore. 
Veda ad esempio
https://www.okpedia.it/do-while-c

Con le parole ciclo "do while" si intende l'iterazione condizionata a un evento
