### ISSUE TITLE
errore battitura file cap.9

### ISSUE THREAD

**Issue by cosimose** [UniprJRC/DSconMATLAB#545]
errore battitura pagina 4 del file graficiAvanzati.
Sostituire L'anteprime con L'anteprima
![errore2](https://github.com/user-attachments/assets/1e739f97-2ad2-48af-b1ec-3f3c8b1faf66)

errore battitura pagina 8 del file graficiAvanzati.
Sostituire costa sarda con Costa Sarda
![errore3](https://github.com/user-attachments/assets/56a46927-48f6-4cf1-946b-80b8054eb243)

**Comment by MarcoRianiUNIPR** [comment]
Anche questo è già stato corretto

![image](https://github.com/user-attachments/assets/2df64f33-461b-43e5-a283-8fd66342047f)

Sul fatto di "costa sarda" oppure "Costa Sarda" mi documenterò con i colleghi
