### ISSUE TITLE
errore di battitura esercizi giappichelli 

### ISSUE THREAD

**Issue by cosimose** [UniprJRC/DSconMATLAB#546]
errore pagina 10 file Associazione
sostituire "del del" con del
![errore4](https://github.com/user-attachments/assets/78d34e71-2feb-462d-a993-1dd17e9f7849)

**Comment by MarcoRianiUNIPR** [comment]
Corretto grazie . Issue aperto fino a quando non sarà corretto nel sito di Giappichelli

**Comment by MarcoRianiUNIPR** [comment]
Corretto nel sito di Giappichelli
