### ISSUE TITLE
errore di battitura esercizi giappichelli

### ISSUE THREAD

**Issue by cosimose** [UniprJRC/DSconMATLAB#547]
errore battitura pagina 2 del file Correlazione
sostituire replicatibilità con replicabilità
![errore5](https://github.com/user-attachments/assets/aaaa9006-f026-4d4f-9044-a00fda05d05c)

**Comment by MarcoRianiUNIPR** [comment]
Corretto grazie . Issue aperto fino a quando non sarà corretto nel sito di Giappichelli

**Comment by MarcoRianiUNIPR** [comment]
Corretto nel sito di Giappichelli
