### ISSUE TITLE
Errore di battitura slide 5, Correlazione.OUT

### ISSUE THREAD

**Issue by Alexf02** [UniprJRC/DSconMATLAB#555]
![IMG_0181](https://github.com/user-attachments/assets/bb0cfa02-d1c9-4481-b372-cd0410bc81cd)

**Comment by MarcoRianiUNIPR** [comment]
Segnalazione corretta. 
Issue aperto fino a quando il file non sarà aggiornato nel sito di Giappichelli

**Comment by MarcoRianiUNIPR** [comment]
Typo corretto nel sito di Giappichelli
