### ISSUE TITLE
ERRORE BATTITURA

### ISSUE THREAD

**Issue by Vittoria378** [UniprJRC/DSconMATLAB#559]
pag. 503, dopo la prima formula: "dove la sommatoria **sia** estende ai primi k valori..." -> credo volesse dire "si estende"
pag. 153 prima riga: "rappresentare le **serie 9** serie storiche in 9 pannelli ..."

**Comment by MarcoRianiUNIPR** [comment]
Il primo refuso non era mai stato segnalato.
Appena aggiunto
![image](https://github.com/user-attachments/assets/12dff0bd-4756-4259-a0ce-109975929746)


Il secondo era già stato segnalato (mi raccomando di controllare la pagina di errata corrige)
![image](https://github.com/user-attachments/assets/b58393e2-3432-4a1c-bf02-1e54052d3199)

La ringrazio per il suo messaggio
