### ISSUE TITLE
Errore per la soluzione dell'esercizio di riepilogo 1.2

### ISSUE THREAD

**Issue by chiara-zaffarano** [UniprJRC/DSconMATLAB#59]
La traccia dell'esercizio 1.2 di riepilogo chiede di creare un cell array 2x4, ma la soluzione online del libro crea una 2x3.                      
Seppur aggiungendo, nei comandi, la matrice identità per l'elemento 2,4 manca l'elemento 1,4.
Inoltre l'elemento 2,4 non viene riportato nel comando finale per creare un cell array.

**Comment by UniprJRC** [comment]
Ha perfettamente ragione. Stiamo ancora attendendo da Giappichelli la possibilità di modificare in autonomia gli esercizi di riepilogo.
Nel frattempo in anteprima la soluzione corretta è di seguito

el11=11:20;
el12=5;
el13=10;
el14=12:-2:2;
el21="Vado al mare";
el22=rand(5,6);
el23=(11:14:32)';
el24=eye(3);

CA={el11 el12 el13 el14; el21 el22 el23 el24};
disp(CA)

**Comment by UniprJRC** [comment]
L'issue viene  chiuso in quanto la soluzione corretta è apparsa sul sito di Giappichelli. Grazie mille per la segnalazione
