### ISSUE TITLE
Errore nel capitolo 9 

### ISSUE THREAD

**Issue by Beatrice-ops** [UniprJRC/DSconMATLAB#590]
Nel capitolo 9, a pagina 319 quarta riga invece che "sovraimporre" ci andrebbe "sovrapporre"

**Comment by MarcoRianiUNIPR** [comment]
La Treccani mi dice che sovraimporre esiste.
![image](https://github.com/user-attachments/assets/2683ce88-5fc5-436e-a278-b3ca97b6bdd3)
Sono d'accordo che sovrapporre è  più comune, ma esiste anche l'altra versione
