### ISSUE TITLE
Errori che non ostacolano la comprensione 

### ISSUE THREAD

**Issue by Beatrice-ops** [UniprJRC/DSconMATLAB#594]
A pagina 67, in fondo per la somma delle matrici, "(A+b)" la "b" andrebbe maiuscola

**Comment by MarcoRianiUNIPR** [comment]
Già segnalato 
Mi raccomando di controllare la pagina di errata corrige
![image](https://github.com/user-attachments/assets/bc2aeac7-eda3-4d23-9b76-4b353ef6f9a6)

In generale se una persona trova un possibile refuso alla p. 67 è sufficiente scrivere 67 nel file mlx
![image](https://github.com/user-attachments/assets/fadf13cc-7ab1-4760-8f5c-7d5df77529af)
