### ISSUE TITLE
errori che non ostacolano la comprensione

### ISSUE THREAD

**Issue by Beatrice-ops** [UniprJRC/DSconMATLAB#595]
A pagina 349 penultima riga, invece che "simmetrice" sarebbe "simmetriche"

**Comment by MarcoRianiUNIPR** [comment]
Stessa cosa di prima
Anche questo è stato già segnalato
![image](https://github.com/user-attachments/assets/0a6132ae-4698-423e-a0af-2d98483a1dee)
