### ISSUE TITLE
Errore nella soluzione Esercizio 14, EserciziExtra Algebrabase

### ISSUE THREAD

**Issue by FrankdeSeriis** [UniprJRC/DSconMATLAB#6]
Nel file EserciziExtraMLXout degli esercizi extra di algebra base, la soluzione dell'esercizio 14 non corrisponde con quella della traccia assegnata, ma a quella di un altro esercizio e quindi risulta impossibile controllare la corretta dei risultati.

**Comment by MarcoRianiUNIPR** [comment]
Chiudo l'issue in quanto era stato corretto a suo tempo. La ringrazio per la segnalazione
