### ISSUE TITLE
Errore sintassi nell'esercizio di riepilogo 2.4 del capitolo 2

### ISSUE THREAD

**Issue by AlbanoSyria2002** [UniprJRC/DSconMATLAB#60]
f(⁓boo)=4*(x(⁓boo).^2)+1;
Giappichelli nella soluzione di questo esercizio inserisce in questo comando il carattere ⁓ , ma eseguendo questo comando su matlab viene segnalato un errore di carattere invalido/non riconosciuto (⁓). Ho risolto comunque l'esercizio senza mettere il carattere ⁓.

**Comment by UniprJRC** [comment]
Il carattere ~ significa not (Questo carattere si inserisce con ALT+126).
In MATLAB può anche fare char(126)
Il carattere che lei ha digitato non è ~ ma ⁓. Se ingrandisce lo schermo può notare la differenza. Il suo carattere appartiene alla codifica di ascii esteso e non è riconosciuto da MATLAB. Probabilmente lo ha inserito tramite i simboli di word e o tramite un copia incolla da altri file.
In altri termini se aggiungiamo 0 alla sua tilde MATLAB produce
 '⁓'+0

ans =

        8275
 
ossia questo carattere ha la codifica ASCII 8275.

Al contrario

 '~'+0

ans =

   126

Per gli utenti "non esperti" i caratteri '~' e '⁓' sono la stessa cosa, ma in ASCII sono codificati in maniera completamente diversa.

**Comment by UniprJRC** [comment]
Nel sito di Giappichelli ora le soluzioni sono riportate con la formattazione corretta. Grazie mille per la segnalazione
