### ISSUE TITLE
Errore battitura slide 6 componenti.OUT

### ISSUE THREAD

**Issue by Alexf02** [UniprJRC/DSconMATLAB#600]
sostituire Schk con Schk1 in quanto l'assert di Schk e stato già effettuato in precedenza. 
![IMG_0298 2](https://github.com/user-attachments/assets/32aac8c0-2b63-410f-959a-682d573e88ee)

**Comment by MarcoRianiUNIPR** [comment]
Osservazione corretta. Bravo!

**Comment by MarcoRianiUNIPR** [comment]
Issue corretto nel sito di Giappichelli
