### ISSUE TITLE
INTERVENTO CONFERENZA

### ISSUE THREAD

**Issue by giadalucchinelli** [UniprJRC/DSconMATLAB#608]
Salve Prof. 
Come da lei richiesto, ho creato questa nuova issue per ricordarle del mio intervento durante la conferenza del giorno 8/11/2024, durante la presentazione del Professore Domenico Vitulano.
Grazie.

**Comment by MarcoRianiUNIPR** [comment]
Questa informazione deve essere inserita nel file che viene consegnato e NON negli issues di GitHub
Di conseguenza, chiudo immediatamente questo issue
