### ISSUE TITLE
Errore di battitura pag.8

### ISSUE THREAD

**Issue by matteocardi16** [UniprJRC/DSconMATLAB#61]
Errore di battitura nell'indice degli argomenti del libro "Data science con Matlab" a pag.8, par. 4.6.1: "Cambiamento della periodicità _delle serie storica_" da cambiare in "Cambiamento della periodicità _delle serie storiche_".

**Comment by UniprJRC** [comment]
Aggiunto all'errata corrige, grazie mille per la segnalazione
