### ISSUE TITLE
Errore di battitura che non ostacola la comprensione del file normEucl 

### ISSUE THREAD

**Issue by RossellaMorillo03** [UniprJRC/DSconMATLAB#610]
Errore di battitura del file normEucl, presente nella cartella dei file DSconMATLAB precisamente nella cartella capAlgebra->CapAlgebraBase che si riferisce all’esercizio del libro n. 10.1. Nel libro non è presente questo errore solo nel file.

![IMG_0762](https://github.com/user-attachments/assets/06d3a169-0f4e-4057-a113-1e61865b4dcf)

**Comment by MarcoRianiUNIPR** [comment]
Corretto grazie

![image](https://github.com/user-attachments/assets/19558ad1-d8a5-4101-8b61-d6609f9b888e)
