### ISSUE TITLE
Errore di battitura che non ostacola la comprensione nel file Rotazione

### ISSUE THREAD

**Issue by RossellaMorillo03** [UniprJRC/DSconMATLAB#611]
Errore di battitura nel file rotazione, presente nella cartella dei file DSconMATLAB precisamente nella cartella capComponentiPrincipali. 

![IMG_0794](https://github.com/user-attachments/assets/e7ed655d-5ee4-493f-aeed-604d8fccefc9)

**Comment by MarcoRianiUNIPR** [comment]
Corretto grazie

![image](https://github.com/user-attachments/assets/f0bc3a40-311b-45bd-b0c7-78125871d9f9)
