### ISSUE TITLE
errore di battitura che non ostacola la comprensione HW13.2 SITO GIAPPICHELLI

### ISSUE THREAD

**Issue by SimoneFls** [UniprJRC/DSconMATLAB#617]
HW13.2 sul SITO GIAPPICHELLI
riga 52 
"caratterizzati da attivitò lavorative ripetitive"
**attivitò lavorative** -> attività lavorative

**Comment by MarcoRianiUNIPR** [comment]
Corretto nel sito di Giappichelli
