### ISSUE TITLE
Errori di battitura che non ostacolano la comprensione ES. 12.3 libro e file

### ISSUE THREAD

**Issue by RossellaMorillo03** [UniprJRC/DSconMATLAB#622]
Errori di battitura che non ostacolano la comprensione es. 12.3 sul libro. Il primo nella riga 22 il secondo nella riga 36. Poi ho controllato il file di riferimento nella cartella DSconMATLAB precisamente nel file Verificaeq1116 il primo errore è scritto correttamente mentre il secondo errore è presente anche nel file.

![IMG_0803](https://github.com/user-attachments/assets/b776146a-d1be-46db-87fc-ac70dba45f1a)

![IMG_0802](https://github.com/user-attachments/assets/2370928c-5b0a-43bd-8d8f-5ca08791c59d)

**Comment by MarcoRianiUNIPR** [comment]
Il primo era già segnalato (ecco perché era già stato corretto)
![image](https://github.com/user-attachments/assets/e0f8ef2a-222c-4475-994d-4c01f6aab06f)

La seconda segnalazione è nuova, la ringrazio.
Errata corrige aggiornata
![image](https://github.com/user-attachments/assets/1d7d2a39-5a91-4513-abf1-e7b1f28917f1)
