### ISSUE TITLE
Errore di battitura che non ostacola la comprensione file corrispINI.m

### ISSUE THREAD

**Issue by RossellaMorillo03** [UniprJRC/DSconMATLAB#624]
Errore di battitura nel file corrispINI.m nella riga 4 che si ripete anche nella riga 254

![IMG_0805](https://github.com/user-attachments/assets/19a01dac-fde0-404c-9a1f-ef4ce7a3eb55)

![IMG_0806](https://github.com/user-attachments/assets/6c2e458e-a4e0-46db-b824-b6928bcee428)

**Comment by MarcoRianiUNIPR** [comment]
File aggiornato, grazie.
