### ISSUE TITLE
Errore di battitura che non ostacola la comprensione

### ISSUE THREAD

**Issue by SILVIAZIZZI** [UniprJRC/DSconMATLAB#631]
Pag 167 ultimo rigo della traccia dell'esercizio 5.1 , "Cosa succede alla densità se..." al posto di "cosa succede alla densità se...", visto che c'è il punto interrogativo prima andrebbe messa la lettera maiuscola

**Comment by MarcoRianiUNIPR** [comment]
Non "andrebbe" ma "va" messa la lettera maiuscola.
Ha assolutamente ragione.
Appena aggiunto in errata corrige

![image](https://github.com/user-attachments/assets/3d9ef2e4-90df-401f-bce3-8aea63607509)

La ringrazio
