### ISSUE TITLE
Errori di battitura che non ostacolano la comprensione

### ISSUE THREAD

**Issue by SILVIAZIZZI** [UniprJRC/DSconMATLAB#632]
pag 393 sotto la seconda table in cui si commentano i risultati delle distanze tra Paesi, c'è scritto "il paese A è MOTO simile al paese C..." che andrebbe cambiato in "molto"

**Comment by MarcoRianiUNIPR** [comment]
Fatto grazie

![image](https://github.com/user-attachments/assets/00849851-4e2b-424d-b5a9-b8f4f5507efb)
