### ISSUE TITLE
Errore di battitura che non ostacola la comprensione

### ISSUE THREAD

**Issue by beatrice-senia** [UniprJRC/DSconMATLAB#634]
A pagina 239 del libro di testo, in riferimento alla descrizione della tabella 7.1, andrebbe cambiato il numero da "7 aeroporti" a "8 aeroporti".

**Comment by beatrice-senia** [comment]
Si ripete lo stesso errore anche nell'esercizio 7.6 a pagina 240
![IMG_3579](https://github.com/user-attachments/assets/6af58c73-b74f-4486-8b12-1d42e33113ff)

**Comment by MarcoRianiUNIPR** [comment]
Fatto grazie

![image](https://github.com/user-attachments/assets/51a4ad39-16cb-4797-91e3-724aa39f1ac3)
