### ISSUE TITLE
Errore di battitura pag.49

### ISSUE THREAD

**Issue by matteocardi16** [UniprJRC/DSconMATLAB#68]
Errore di battitura alla riga 8 di pagina 49: cambiare "Age" con "Wage".

**Comment by UniprJRC** [comment]
Aggiunto in errata corrige. Grazie per la segnalazione

p. 49 riga 8 della sezione 1.5.4 (segnalato da matteocardi16 23/09/2023)
Rimpiazzare
...le variabili denominate "Seniority" e "Age"...
con
...le variabili denominate "Seniority" e "Wage"...
