### ISSUE TITLE
salve  bouna sera prof io no riuscito  di scaricare il fail di github perche ogni volta scarica dopo lo metto !git mi ucere non vailed anche il fail di corso 

### ISSUE THREAD

**Issue by sayefyonko** [UniprJRC/DSconMATLAB#69]
saleve bouna sera prof io no recuto di scaricare il fail di github perche ogni volta scarica dopo lo metto !git mi ucere non vailed

_Originally posted by @sayefyonko in https://github.com/UniprJRC/DSconMATLAB/issues/13#issuecomment-1732318607_

**Comment by UniprJRC** [comment]
La cosa migliore è vedersi nelle lezioni presso le aule dei laboratori e/o sentirci con Teams e condivisione schermo.

**Comment by UniprJRC** [comment]
chiudo l'issue mi faccia sapere se ora è tutto a posto
