### ISSUE TITLE
errore ortografico

### ISSUE THREAD

**Issue by benedettacrux25** [UniprJRC/DSconMATLAB#7]
File normaleintro (cap distribuzioni) riga 8 
Rimpiazzare ‘tramita’ con ‘tramite’

**Comment by MarcoRianiUNIPR** [comment]
Aggiunto il suo nome alla pagina di errata corrige

4) Cosa succede...

riga 8 del codice rimpiazzare
% Calcolo della densità tramita ...
con
% Calcolo della densità tramite ...
Segnalato da Paola Serlunghi e benedettacrux25
