### ISSUE TITLE
Segnalazione mancanza soluzione esercizio HW 1.4

### ISSUE THREAD

**Issue by lucachiossi98** [UniprJRC/DSconMATLAB#73]
Manca la soluzione del quarto punto dell'esercizio HW 1.4 dove deve essere utilizzato l'indicatore booeliano "&"
soluzione corretta--> crit=USA.UrbanPop>70 & USA.Murder>12;
Chiossi Luca e Mattia Capuzzo

**Comment by UniprJRC** [comment]
Questa segnalazione si riferisce al sito Giappichelli ed è stata taggata "Sito Giappichelli". 
L'osservazione è assolutamente corretta. In data 27/05/2023 abbiamo un incontro con lo staff di Giappichelli per capire se ci danno i diritti di scrittura sul loro sito.
Per le nuove segnalazioni che si riferiscono al sito di Giappichelli per favore utilizzare il tag "Sito Giappichelli"

**Comment by UniprJRC** [comment]
Il sito di Giappichelli delle soluzioni agli esercizi di riepilogo è stato aggiornato e la soluzione al quarto punto è stata aggiunta
