### ISSUE TITLE
errore di battitura ultima riga pagina 138

### ISSUE THREAD

**Issue by FrancescaPiaSarno** [UniprJRC/DSconMATLAB#75]
Sostituire la parola **colonne** con **colonna**

**Comment by UniprJRC** [comment]
Appena inserito in errata corrige
----------------------------
p. 138 ultima riga della pagina prima del riquadro del codice (segnalato da Francesca Pia Sarno 27/09/2023)
Rimpiazzare
...nella colonne della nuova table)...
con
...nelle colonne della nuova table)...

**Comment by UniprJRC** [comment]
Grazie mille per la segnalazione
