### ISSUE TITLE
Errore esercizio 3.8, pagina 118-119

### ISSUE THREAD

**Issue by federico-baio** [UniprJRC/DSconMATLAB#79]
Il punto due dell'esercizio chiede di mostrare le prime 6 colonne di XtabComplessiva nella Command Window. Il codice e l'output dell'esercizio mostrano però le prime 7 colonne. 
la riga 11 del codice riporta infatti-->disp(XtabComplessiva(:,1:7))

**Comment by UniprJRC** [comment]
Segnalazione corretta ed inserita in errata nella sezione "errori che possono ostacolare la comprensione"
