### ISSUE TITLE
ERRORE

### ISSUE THREAD

**Issue by jessica-bondavalli** [UniprJRC/DSconMATLAB#8]
Pag .191
Esercizio 7.2
nella linea 20 rimpiazzare 
%La statistica di Pearson si distriuisce come una v.c...
con 
%La statistica di Pearson si distribuisce come una v.c.

**Comment by MarcoRianiUNIPR** [comment]
Stessa cosa per questa segnalazione. Grazie ancora una volta.

p. 191 riga 20 del codice
Rimpiazzare
...si distriuisce come una v.c. Chi2...
con
...si distribuisce come una v.c. Chi2...
Segnalato da Jessica Bondavalli
