### ISSUE TITLE
Imprecisazione/errore pagina 98 Esercizio 3.3

### ISSUE THREAD

**Issue by FicSte** [UniprJRC/DSconMATLAB#80]
Durante la consegna dell'esercizio, e nei commenti del codice, viene utilizzata la variabile "Xd", mentre nel codice viene utilizzata "Xdq". L'altra variaile "Xtq" viene invece correttamente definita sia nella consegna, che nei commenti, che sul codice.
Stefano Ficiarà

**Comment by UniprJRC** [comment]
Mi raccomando di controllare la pagina di errata corrige prima di scrivere


Dalla pagina di errata corrige

p. 96 prima riga dell'Esercizio 3.3 (segnalato da Dallo2001 25/09/2023)
Rimpiazzare
...estrarre il contenuto delle variabili quantitative (ad eccezione della data di nascita) in un array denominato Xd.
con
...estrarre il contenuto delle variabili quantitative (ad eccezione della data di nascita) in un array denominato Xdq.
Nel righe 1:3 del codice di p. 98, similmente, quando di parla di array denominato Xd ci si riferisce all'array  Xdq. Il testo corretto è 
% Estrazione delle variabili quantitative nell'array Xdq e nella table Xtq
% Osservazione: Xdq contiene solo i numeri (matrice 107x4 di doubles)
% Xtq è la table (107x4) riferita solo alle variabile quantitative
