### ISSUE TITLE
Errore battitura pagina 41

### ISSUE THREAD

**Issue by Rajaramzii** [UniprJRC/DSconMATLAB#83]
Errore battitura tabella pagina 41, sostituire "causali" con "casuali"

**Comment by UniprJRC** [comment]
Mi raccomando prima di scrivere di controllare la pagina di errata corrige

p. 41 Tabella 1.1 (segnalato da Francesca Pia Sarno 19/09/2023)
Nel riquadro di sinistra in basso della Tabella 1.1 rimpiazzare "numeri causali" con "numeri casuali"
