### ISSUE TITLE
errore pagina 143 esercizio 4.3

### ISSUE THREAD

**Issue by giorgialusardi** [UniprJRC/DSconMATLAB#87]
Nell'esercizio 4.3 nella prima riga invece di scrivere "...in una table le informazioni contenut**i** nel file", si doveva scrivere "...in una table le informazioni contenut**e** nel file"

**Comment by UniprJRC** [comment]
Appena agigunto in errata corrige grazie mille

p. 143 prima riga Esercizio 4.3 (segnalato da [giorgialusardi](https://github.com/giorgialusardi) 29/09/2023)
Rimpiazzare
"...in una table le informazioni contenuti nel file", 
con
 "...in una table le informazioni contenute nel file"
