### ISSUE TITLE
Errore di battitura pag 64

### ISSUE THREAD

**Issue by lucachiossi98** [UniprJRC/DSconMATLAB#88]
nel capitolo 1.8.5, nella seconda riga "plot (x,y, 'opzioni') dove x e y sono i vettori. nel libro c'è scritto "dove x e v sono i vettori". da sostituire y con v

**Comment by UniprJRC** [comment]
Mi raccomando di consultare la pagina di errata corrige prima di scrivere
------------------------------------
p. 64 seconda riga della sezione 1.8.5 (segnalato da [federico-baio](https://github.com/federico-baio) 20/09/2023)
Rimpiazzare
...dove x e v sono i vettori di dati...
con
...dove x e y sono i vettori di dati...

**Comment by UniprJRC** [comment]
issue già segnalato
