### ISSUE TITLE
errore pag.145

### ISSUE THREAD

**Issue by OrlandiMartina** [UniprJRC/DSconMATLAB#89]
Pag 145, paragrafo 4.4, prima riga
 Sostituire: 
in cui ogni riga corrisponde
con
in cui **ad** ogni riga corrisponde

**Comment by UniprJRC** [comment]
Fatto grazie

p. 145, sezione 4.4, prima riga (segnato da  [Orlandi Martina](https://github.com/OrlandiMartina) 29/09/2023)
Sostituire:
in cui ogni riga corrisponde
con
in cui ad ogni riga corrisponde
