### ISSUE TITLE
Errore pag.153

### ISSUE THREAD

**Issue by OrlandiMartina** [UniprJRC/DSconMATLAB#91]
pag.153, prima riga
sostituire 
Rappresentare le **serie** 9 serie
con:
Rappresentare le 9 serie

**Comment by UniprJRC** [comment]
Grazie di nuovo.
----------------------

p. 153 prima riga (segnalato da [Orlandi Martina](https://github.com/OrlandiMartina) 29/09/2023)
Rimpiazzare
Rappresentare le serie 9 serie storiche...
con
Rappresentare le 9 serie storiche...
