### ISSUE TITLE
Errore di battitura che non ostacola la comprensione del testo

### ISSUE THREAD

**Issue by Gioele090101** [UniprJRC/DSconMATLAB#92]
Pag.121 par.3.7 riga 7:    Nella schemata riportata nella Figura 3.12.....
                                    è corretto scrivere:  Nella schermata riportata nella Figura 3.12

                                       Manca la "r" nella parola "schemata.

**Comment by UniprJRC** [comment]
Fatto grazie
--------------------
p. 121 riga 7 della sezione 3.7 (segnalato da [Gioele090101](https://github.com/Gioele090101) 29/09/2023)
Rimpiazzare
... Nella schemata riporta nella Figura 3.12...
con
... Nella schermata riporta nella Figura 3.12...
